<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoKontrak</name>
   <tag></tag>
   <elementGuidId>d3c7aa4c-199f-4fb3-8473-39ea7d6bd3ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;referenceNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;referenceNo&quot;]</value>
      <webElementGuid>0e9e6f34-0a92-4972-9c16-aac501c37a83</webElementGuid>
   </webElementProperties>
</WebElementEntity>
