<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalTrxDari</name>
   <tag></tag>
   <elementGuidId>39de6b2f-5ad8-4614-bf52-ac9787eb62e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;transactionDateStart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;transactionDateStart&quot;]</value>
      <webElementGuid>6cfbf8a3-14fa-4d38-9d31-d17bc94e9a2b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
