<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Salin</name>
   <tag></tag>
   <elementGuidId>fe36d8dc-4cd3-436b-b366-9f30d168351f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-view-invitation-link/div/div[1]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-view-invitation-link/div/div[1]/div[2]/button</value>
      <webElementGuid>d2c819e0-353b-464d-86fa-246456bf450b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
