<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EmailNew</name>
   <tag></tag>
   <elementGuidId>1bf0e24e-40bd-4bf2-aa8a-b5a351b18cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'loginId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='loginId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7961dce1-f107-4eb0-9102-a2f8acfb16e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginId</value>
      <webElementGuid>9cd9cbc8-ca57-4903-8822-44f65f69934c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='loginId']</value>
      <webElementGuid>b6a7399c-8b29-42c8-a37b-791a4672b5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-text/fieldset/div/input</value>
      <webElementGuid>baf53b7e-d356-47a2-a6d4-85fa9dd3a5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'loginId' and @placeholder = 'Tulis email Anda']</value>
      <webElementGuid>eb9c3bb1-aadd-4684-88b3-06ffa5908f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
