<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PeranEdit</name>
   <tag></tag>
   <elementGuidId>b529de54-4dee-463c-8b24-0090a5a12f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#officeCode > div.ng-select-container.ng-has-value > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;roleCode&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;roleCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>df6252ae-c568-4718-9098-4622e372faf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[5]</value>
      <webElementGuid>8ad37d3d-cb27-4979-81db-1123c03d8565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='officeCode']/div/div/div[3]/input</value>
      <webElementGuid>c6fccbcd-b47b-456e-a5fc-7d771faadc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/app-select/div/div[2]/ng-select/div/div/div[3]/input</value>
      <webElementGuid>2a774f07-4a5a-42aa-b645-955e7493acfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>2590cc9d-6270-41e2-a194-e391f352862b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
