<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UlangKataSandi</name>
   <tag></tag>
   <elementGuidId>7874edc9-8ac1-4f31-a4b3-eca089aaf574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[4]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[4]/div[1]/input</value>
      <webElementGuid>f9c4549e-9a6c-44d1-b98d-67c55530b27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>76da111a-70c7-476c-ad8d-48e3e6ab61a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
