<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kirimKodeLagi</name>
   <tag></tag>
   <elementGuidId>00ba871c-f057-4e8e-84d9-6a5d47bfe9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-modal-request-otp/form/div/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-modal-request-otp/form/div/div[5]/div/a</value>
      <webElementGuid>b6f52fcc-03ef-4a1f-b3d0-d44ca8e9e430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim kode lagi</value>
      <webElementGuid>1faf09cb-e78f-42d1-83c4-a141f3fd3a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reset-button</value>
      <webElementGuid>bab32543-1432-409f-a27c-646e99c1c892</webElementGuid>
   </webElementProperties>
</WebElementEntity>
