<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wilayah</name>
   <tag></tag>
   <elementGuidId>9eead5b2-4e4c-411b-afca-6a8c5e83e3bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;region&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;region&quot;]</value>
      <webElementGuid>1d441929-aa44-4ea2-83bb-6d118229207d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
