<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kelurahan</name>
   <tag></tag>
   <elementGuidId>183ea1bf-0055-4c31-80a1-dd4724541543</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subDistrict&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subDistrict&quot;]</value>
      <webElementGuid>09312d09-4ca2-405c-91a0-0e71bf9b6618</webElementGuid>
   </webElementProperties>
</WebElementEntity>
