<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LiniBisnis</name>
   <tag></tag>
   <elementGuidId>b0120757-9abc-464b-ae5a-b5b1f2ddde17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;businessLine&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;businessLine&quot;]</value>
      <webElementGuid>db231643-bf85-4b91-9ec6-0458969a7430</webElementGuid>
   </webElementProperties>
</WebElementEntity>
