<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Office</name>
   <tag></tag>
   <elementGuidId>92aba47b-5a16-462c-8dac-e65c15bb05a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;office&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;office&quot;]</value>
      <webElementGuid>283e29cb-d162-4a92-9279-0885c37a4b93</webElementGuid>
   </webElementProperties>
</WebElementEntity>
