<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SMSNotif</name>
   <tag></tag>
   <elementGuidId>caa8b980-0964-46e0-8ef1-a53a5ac58bfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;SMS&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;SMS&quot;]</value>
      <webElementGuid>476e28c2-a09e-4de4-9279-c519239d6aa3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
