<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OCRSTNK</name>
   <tag></tag>
   <elementGuidId>66b681a2-5a42-4ee0-909d-307fcc810ddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;OCR_STNK&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;OCR_STNK&quot;]</value>
      <webElementGuid>aeb55067-bff7-4059-b0d4-95d7dae28b75</webElementGuid>
   </webElementProperties>
</WebElementEntity>
