<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VerifikasiWajah</name>
   <tag></tag>
   <elementGuidId>89ff4d84-e03a-4ea2-b50c-6fa3e3fd248f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;FVRF&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;FVRF&quot;]</value>
      <webElementGuid>1c505f54-4a52-431e-8a54-bfe398bdcde1</webElementGuid>
   </webElementProperties>
</WebElementEntity>
