<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OCRNPWP</name>
   <tag></tag>
   <elementGuidId>d595acae-a9b1-41b8-af62-315376f35ef2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;OCR_NPWP&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;OCR_NPWP&quot;]</value>
      <webElementGuid>cd0343ec-ea62-4acc-b62f-4ea7f4b856f0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
