<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DukcapilBiometrik</name>
   <tag></tag>
   <elementGuidId>a1d11f44-efe7-4e8b-9de4-b93a50bff75d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;DUKBIO&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DUKBIO&quot;]</value>
      <webElementGuid>6ae2cdb5-b687-463d-b237-cdb61ed628cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
