<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokumen</name>
   <tag></tag>
   <elementGuidId>1ae1313e-0822-4ca1-ad8b-8e6c088d9b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;DOC&quot;]</value>
      <webElementGuid>b8372cba-cfa6-4f08-b1d5-3a6dccbe953a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
