<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPengirimanDari</name>
   <tag></tag>
   <elementGuidId>700e07b7-3e0a-47a5-a075-4cba745873aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tanggalPengirimanDari&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tanggalPengirimanDari&quot;]</value>
      <webElementGuid>e1558929-941f-4f2e-aa00-7c7ef669ad77</webElementGuid>
   </webElementProperties>
</WebElementEntity>
