<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_confirmNewPass</name>
   <tag></tag>
   <elementGuidId>d6cf0601-8434-4ab9-8572-55b6637c0788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirmNewPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='confirmNewPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26d1a15c-5250-46b2-b219-ebeb5b404bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ea8e5c56-85da-4331-8e5b-7a89dd22a3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>219449dd-d27c-4d9c-aad1-0de9a602754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirmNewPassword</value>
      <webElementGuid>6d909712-d14e-413d-9368-acfb5e2d1819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cbe7c4f0-ded4-48e9-a19e-86ca4ab8a506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Konfirmasi Kode Akses Baru</value>
      <webElementGuid>aa790ebe-2c75-42be-bb71-dfc4ef192dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>684ea0c7-3984-4396-8ea8-d9867ae1b0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirmNewPassword&quot;)</value>
      <webElementGuid>e400955f-388a-4d82-b551-147a9774662d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='confirmNewPassword']</value>
      <webElementGuid>d81eb571-f76a-4ca6-b5e1-cea6a51c01df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>35508397-46b3-4ee1-b9e5-f26a1b92b86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-password/fieldset/div/input</value>
      <webElementGuid>c47a5b72-b041-42d8-89d1-0e44b70a5d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'confirmNewPassword' and @type = 'password' and @placeholder = 'Konfirmasi Kode Akses Baru']</value>
      <webElementGuid>f10c9cda-ad36-4e2f-b1bc-6481b839f138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
