<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_popup</name>
   <tag></tag>
   <elementGuidId>2cfa776e-f233-4731-bd8b-5cfbe72585ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;swal2-content&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;swal2-content&quot;]</value>
      <webElementGuid>75820c3b-3e69-4877-b46e-956a2d0d6495</webElementGuid>
   </webElementProperties>
</WebElementEntity>
