<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KodeVendor</name>
   <tag></tag>
   <elementGuidId>cbf96174-bf43-4215-a218-d01794734a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;vendorCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vendorCode&quot;]</value>
      <webElementGuid>0b363156-4f67-473a-beef-a6b26911ec0f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
