<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_MataKataSandi</name>
   <tag></tag>
   <elementGuidId>7e2a4001-a5b5-429c-a567-595d1e704c3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[3]/div[1]/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[3]/div[1]/i[2]</value>
      <webElementGuid>9837047c-962a-4788-8b88-b7cdc885b169</webElementGuid>
   </webElementProperties>
</WebElementEntity>
