<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UlangKataSandi</name>
   <tag></tag>
   <elementGuidId>7874edc9-8ac1-4f31-a4b3-eca089aaf574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[4]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[4]/div[1]/input</value>
      <webElementGuid>6a99693b-24e8-4db1-8334-1052ba5a8907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>94293ae8-e09c-4965-a3a4-c73006a2d2a3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
