<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>kirimKodeLagi</name>
   <tag></tag>
   <elementGuidId>00ba871c-f057-4e8e-84d9-6a5d47bfe9d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Kirim kode lagi' or . = 'Kirim kode lagi') and @class = 'reset-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-modal-request-otp/form/div/div[5]/div/a</value>
      <webElementGuid>4d99f93e-ec59-49ff-adc7-4dd6eacefdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kirim kode lagi</value>
      <webElementGuid>847d9826-8d5c-40d6-bce0-48cc937a5367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reset-button</value>
      <webElementGuid>f5fa4e6f-bc07-4e4e-a972-7d01070f92b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
