<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_URLRedirectTTD</name>
   <tag></tag>
   <elementGuidId>6675ff4c-09c7-41da-a342-4327e504d142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientSigningRedirectUrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientSigningRedirectUrl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>359f0587-6db0-447b-bb8d-45bdd6df9ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis URL Redirect Tanda Tangan</value>
      <webElementGuid>645840d7-2f82-4399-92b5-ef1749618370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientSigningRedirectUrl</value>
      <webElementGuid>12c9c160-cb57-4ff6-9290-65764a4b999a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientSigningRedirectUrl</value>
      <webElementGuid>a44e4937-c974-41a4-a434-aba530498843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-8 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>19adf866-43d0-4f0f-9b88-76bceef75d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>clientSigningRedirectUrl</value>
      <webElementGuid>abb028f4-e2bc-4761-80e9-9e17c60c0427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientSigningRedirectUrl&quot;)</value>
      <webElementGuid>b912f133-fb63-4922-9b90-7fe9b350ac0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientSigningRedirectUrl']</value>
      <webElementGuid>94eb1369-75c7-4ac1-bfe1-852d724efa00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[37]/input</value>
      <webElementGuid>4e033311-28ea-4ae5-8589-a152f48e63d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis URL Redirect Tanda Tangan' and @id = 'clientSigningRedirectUrl']</value>
      <webElementGuid>3120e6e2-8d71-4177-9c73-1f2fd0072e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
