<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_URLUpload</name>
   <tag></tag>
   <elementGuidId>50a42a98-8ddc-45a7-8c4d-30b157645527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadUrl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'uploadUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2180d2ce-1681-4b99-8b84-e929ae57d9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis URL Upload</value>
      <webElementGuid>42c95841-b08e-4e75-a2ed-b04abf91b25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>uploadUrl</value>
      <webElementGuid>3307cfc3-49fc-40d2-a8fd-85413b76f5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadUrl</value>
      <webElementGuid>657f4c1d-0377-4af0-8ef1-5fddfb40ae4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-8 ng-pristine ng-valid ng-touched</value>
      <webElementGuid>2b392ddc-58ea-45c7-a922-9b2630f7659b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>uploadUrl</value>
      <webElementGuid>af56e1cb-6e1b-4d96-a605-575dcf71e1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadUrl&quot;)</value>
      <webElementGuid>2295ca34-986a-4583-b73a-811af2ade012</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadUrl']</value>
      <webElementGuid>f5cd5eb8-2218-498a-907c-4c34b7116ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9b333d0d-3a27-43ad-902b-bcb84cf7e5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis URL Upload' and @id = 'uploadUrl']</value>
      <webElementGuid>42fcf362-5e30-4000-bbc2-0b904406b3dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
