<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tambah_activationCallbackUrl</name>
   <tag></tag>
   <elementGuidId>c5248e3c-5b66-455e-9ddc-5b6325666531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='activationCallbackUrl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'activationCallbackUrl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#activationCallbackUrl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aec762c3-2127-4b4f-89f9-732980afe05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis URL Callback Aktivasi</value>
      <webElementGuid>ab403e52-3efc-4595-8b8d-88b59dc7930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>activationCallbackUrl</value>
      <webElementGuid>d5af1c15-d8c4-4b96-a700-0cb8e0948a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>activationCallbackUrl</value>
      <webElementGuid>b80439e2-4eaf-4811-8970-0a0e180aa092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-8 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>049533b0-41fe-410b-b9b0-d04802bb5100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>activationCallbackUrl</value>
      <webElementGuid>dff3fa36-dbc8-40aa-9039-ae8ad4ede72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;activationCallbackUrl&quot;)</value>
      <webElementGuid>1d6bd1b8-c8ff-4337-ab3c-cee9fd038d79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='activationCallbackUrl']</value>
      <webElementGuid>62504951-5f06-453d-81fe-df8688522e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/input</value>
      <webElementGuid>78c25a6d-e5ea-490d-95b5-5cc6d04c8c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis URL Callback Aktivasi' and @id = 'activationCallbackUrl']</value>
      <webElementGuid>bbf40f75-a451-4a1f-9eae-ae45a9451f8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
