<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BatasSaldo</name>
   <tag></tag>
   <elementGuidId>ac99a89c-d774-4858-855f-c5ebe970e3e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OTP']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'OTP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7548133f-415e-4029-94c9-c1233a0fde81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>812d61e9-2c09-4aac-95d8-01c802ce7dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2fd90b81-5dc1-47ec-b4be-09c81353b375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-1 col-2</value>
      <webElementGuid>f038dcdb-e34c-46c3-a797-c3f4ba9a6458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a20d7439-ea1c-42db-9390-3eec56de0303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>OTP</value>
      <webElementGuid>e9f1c4a2-ffc4-4f3c-8e42-9e81c5593eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTP</value>
      <webElementGuid>f9c28c45-a6dd-4e24-97db-a529e2bc133f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTP&quot;)</value>
      <webElementGuid>6093ed66-2eaf-49c9-8dff-ef7407e95287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OTP']</value>
      <webElementGuid>84db2cb7-7718-484d-8d23-2de2f645fb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>3eaa95d9-4b9b-4ab7-9963-b58cf784ca4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'OTP']</value>
      <webElementGuid>5c611ef6-5812-407c-a1ae-d2f84ddc5bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
