<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PenerimaEmailReminderSaldo</name>
   <tag></tag>
   <elementGuidId>da089f35-46eb-4c62-9945-e6672d398a50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-tenant-settings/div[2]/div/div/div/div/form/div[20]/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.col-5.ng-valid.ng-touched.ng-dirty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[20]/div/input</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>788a4806-927d-4bb9-9f68-8870a39e381b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis email</value>
      <webElementGuid>bf18f87f-cea9-407a-ac9a-60f5f6da7984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-5 ng-valid ng-touched ng-dirty</value>
      <webElementGuid>8c27b027-f994-47aa-b7ab-74cd3401c290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>ANDY@AD-INS.COM</value>
      <webElementGuid>bb18401c-17da-40da-9983-75893149a749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-options</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>68ba48c1-a5b0-4cad-ae63-9e1bf6ec468f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-tenant-settings/div[2]/div/div/div/div/form/div[20]/div/input</value>
      <webElementGuid>21d8b6a3-ac7e-4b9a-8366-13ebd779f40a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/input</value>
      <webElementGuid>3ff0c3ce-dbf3-4c38-ad2c-a8a4cbab96f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis email']</value>
      <webElementGuid>7e1167f1-688c-403f-871f-04c442c1f029</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
