<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_URLAktivasiRedirect</name>
   <tag></tag>
   <elementGuidId>c59920d8-a677-4d8a-bf8d-5c1c2dd09364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientActivationRedirectUrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientActivationRedirectUrl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fe580d2-c3c3-4430-8a62-c7dd66cb5928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis URL Redirect Aktivasi</value>
      <webElementGuid>ba01d1bc-c334-43ba-9895-5f726beed953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientActivationRedirectUrl</value>
      <webElementGuid>d781f432-dcee-4a1f-b4a7-f59942c84502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientActivationRedirectUrl</value>
      <webElementGuid>5aa80b8d-5a87-41a4-80b0-e0013ea094d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-8 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>a1d71099-02ba-4e22-b98e-9613b26aeee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>clientActivationRedirectUrl</value>
      <webElementGuid>d45e9c4d-b678-4046-badf-6c242a133250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientActivationRedirectUrl&quot;)</value>
      <webElementGuid>8186fecc-2b3a-4dbd-bd40-0ce4cd1f3e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientActivationRedirectUrl']</value>
      <webElementGuid>c8cd1b95-263b-4da7-a24d-ac56da455868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[35]/input</value>
      <webElementGuid>8301c906-8bb2-4eed-9b8f-d75bf298ff27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis URL Redirect Aktivasi' and @id = 'clientActivationRedirectUrl']</value>
      <webElementGuid>ea006c1d-6f5b-4fbb-99ca-554bf3c18cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
