<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LabelRefNumber</name>
   <tag></tag>
   <elementGuidId>c659e7e3-ce99-429d-b6e4-05ed57cc02e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refNumberLabel']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'refNumberLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#refNumberLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee7eb1c9-efad-4617-862f-569e9445e28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c8b699b-83a5-4985-b5d9-76aa65e54274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>refNumberLabel</value>
      <webElementGuid>aba21525-3b4e-47e3-9ae5-879e03e9f5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refNumberLabel</value>
      <webElementGuid>77506c08-0a4c-44e2-8efc-77897fcbf2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-1 col-5 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3b6543b0-09f1-4f62-9ea0-f8c16141d877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>refNumberLabel</value>
      <webElementGuid>e6ef8357-399f-4889-b212-1a757ecd8119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refNumberLabel&quot;)</value>
      <webElementGuid>c7b3d394-5c3b-4d99-ab3c-f67a8b709f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refNumberLabel']</value>
      <webElementGuid>dd3b8582-be82-4aab-92ce-9a16fb8633fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>fe13a6d4-ebe6-4d86-88ea-9d930f3bc3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refNumberLabel']</value>
      <webElementGuid>fd7079e3-d658-415f-ac8f-bbe73fef3004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
