<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_URL callback</name>
   <tag></tag>
   <elementGuidId>c3f3c8f3-e047-427c-81d4-5a44df496ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientCallbackUrl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientCallbackUrl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9071afb-34b0-4eb6-8d63-2308cbdcc7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis URL Callback</value>
      <webElementGuid>40d7c3b5-14cf-4f4d-b4b1-eadc0b970963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>clientCallbackUrl</value>
      <webElementGuid>de3bf0a1-0fdc-4c25-9f9c-e4142e40b3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientCallbackUrl</value>
      <webElementGuid>68ab267b-8d8f-4eb9-a5b9-af4488d23d8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control col-8 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4b4ffdc2-4301-48ef-8b9a-353424898456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>clientCallbackUrl</value>
      <webElementGuid>fc369239-6178-4006-9d72-163d3c3e409e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientCallbackUrl&quot;)</value>
      <webElementGuid>5f4024d9-7373-422f-b6e2-d6c261d25bbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientCallbackUrl']</value>
      <webElementGuid>c191517b-c91d-4463-a8cc-3d740e567d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/input</value>
      <webElementGuid>c9229abc-9874-458b-8526-064750539155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tulis URL Callback' and @id = 'clientCallbackUrl']</value>
      <webElementGuid>00befd39-e73d-4e3d-abc7-909d1f7b341e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
