<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radiobtn_useNotifWA</name>
   <tag></tag>
   <elementGuidId>3fcaf46f-3d95-4e78-840a-3a06fa041bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridRadios2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridRadios2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc429d50-1d71-4bdf-b956-b4732c3ce808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>942b63d4-b888-46bc-871c-1e95ece21cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>14513fd1-63a7-4ab9-8839-86bc3afa0efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>794554ff-fdbf-4a52-a3fb-c38566ad3ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridRadios2</value>
      <webElementGuid>24eb6b7a-5bf4-40c6-bdb7-cf9f8fc8e550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3f5eee12-7da7-4a74-af6e-0021349c206c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input radio-pengiriman-notifikasi ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>cc008b87-bcaf-4853-82b1-469ec4a0be47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>c7e5179b-8cea-401c-a094-442653d10f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form-control-name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>53f8a820-cbe9-475e-a7d0-e401d1f7bbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23e89feb-0ec6-4645-8e90-08c7750b2f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridRadios2&quot;)</value>
      <webElementGuid>c6ab3011-d9ba-432a-b630-2764d3b48321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridRadios2']</value>
      <webElementGuid>3ee13447-12aa-4eaf-a4b1-41adf386e4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/input</value>
      <webElementGuid>1b08ba27-fc2a-4774-82c3-cf8f966ad7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'useWaMessage' and @id = 'gridRadios2']</value>
      <webElementGuid>c0dc21f6-48ce-425c-b053-f38374dbca64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
