<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radiobtn_useNotifSMS</name>
   <tag></tag>
   <elementGuidId>dfec0c5d-4b69-477f-8247-10d2916cec04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridRadios1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridRadios1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e05d09d4-a0e6-4372-84e9-c178e30202b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>8dfb649c-74e0-447b-9894-e7b33fd4a205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f2393bbe-317e-4c3a-b41a-96d264277ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>5907bdee-8cb3-4f56-b618-8bd9ad613e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridRadios1</value>
      <webElementGuid>17f4588b-d671-4bbf-a121-5507c6333bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>810d057e-4dc2-4b60-8b86-ed4702533ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input radio-pengiriman-notifikasi ng-dirty ng-valid ng-touched</value>
      <webElementGuid>a6f493c6-822f-4144-ab5b-68056907eb13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>80664d10-9449-4d80-b675-4c6f290d2959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-form-control-name</name>
      <type>Main</type>
      <value>useWaMessage</value>
      <webElementGuid>0ec4c1c0-0777-4d10-84f0-24ce185ab077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa5e3d03-5417-4c68-aea5-8cfa6798bf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridRadios1&quot;)</value>
      <webElementGuid>57153cb0-ccbb-4807-831c-4f06418b0952</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridRadios1']</value>
      <webElementGuid>a57d75bf-d72c-4445-bc9e-ffdd9558ca6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/input</value>
      <webElementGuid>9754541d-6f31-4e21-a45e-e722292665af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'useWaMessage' and @id = 'gridRadios1']</value>
      <webElementGuid>6c943b8e-af3c-45be-bfdd-f027c523a482</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
