<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slide_StampingOtomatis</name>
   <tag></tag>
   <elementGuidId>666fd46f-8546-47e4-bf83-653c5840a889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slider.round</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'slider round']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>274da5bf-8724-4438-8ab5-6c5bcc3fa13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider round</value>
      <webElementGuid>334fe020-339c-487e-b470-eb8498d6e87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-tenant-settings/div[2]/div/div/div/div/form/label/span</value>
      <webElementGuid>17cbedf4-3ae1-4a7c-b575-3ef7380e0973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>140133e8-8a55-4051-9a09-aa489d99c973</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
