<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalTrxSampai</name>
   <tag></tag>
   <elementGuidId>d9f2ed9f-4813-4f3e-8f19-9ad2678d72d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;transactionDateEnd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;transactionDateEnd&quot;]</value>
      <webElementGuid>9b414192-7656-4dc9-a02f-aa04b1fec4c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
