<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyObject</name>
   <tag></tag>
   <elementGuidId>c51d9bca-96b6-4dab-b0f8-8fe1210371f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-balance/div/div/div/div[2]/div/div/div/div/div[1]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-balance/div/div/div/div[2]/div/div/div/div/div[1]/h3</value>
      <webElementGuid>b3ee206a-23aa-434b-a980-82edb65c281d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
