<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bahasa_Inggris</name>
   <tag></tag>
   <elementGuidId>2c98d57a-a58a-4d79-9813-004c1d362be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarSupportedContent']/ul/li/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-small-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8a342d61-38fe-4f88-a4ca-a339ed3f9259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-small-3</value>
      <webElementGuid>33c668f1-434c-4256-8267-4e26ee87f17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>5437e389-3b3e-437c-a6cf-e568d4e1f810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navbarSupportedContent&quot;]/ul/li[1]/div/a[1]/span</value>
      <webElementGuid>0a25362c-8156-46e2-b0c0-f4ee0a96d756</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li/div/a/span</value>
      <webElementGuid>9441191b-ff77-407a-8050-ff686e8c3e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[1]/following::span[1]</value>
      <webElementGuid>7f88f5ef-2ad1-469b-8e71-ed6cb6a8bbae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesian'])[2]/preceding::span[1]</value>
      <webElementGuid>4d1e1f72-78d2-4c8e-b043-744ead7e9b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMIN TAFS'])[1]/preceding::span[2]</value>
      <webElementGuid>41d6ca7d-2efe-41ef-b9fa-0e3091f3be51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='English']/parent::*</value>
      <webElementGuid>3873aefd-7bf3-4d06-ae31-4342c19942b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>a7fe43b1-a8f0-4cee-b80e-ef5aecdd36ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'English' or . = 'English')]</value>
      <webElementGuid>680d0704-32de-4fde-99a5-ee9a237d4f0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
