<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tipesaldo</name>
   <tag></tag>
   <elementGuidId>b02e6ce2-bf36-48d5-b946-bf457ac18c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;balanceType&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;balanceType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>a29e07e9-cabe-47fb-b513-e40691dd7d6c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
