<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_fromdate</name>
   <tag></tag>
   <elementGuidId>9d9bed42-e854-4cb5-a4fa-2ff525f57262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;transactionDateStart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;transactionDateStart&quot;]</value>
      <webElementGuid>73cadec1-cfc4-4530-b3ca-e98cbb73ebca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
