<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_todate</name>
   <tag></tag>
   <elementGuidId>cdb56a2f-196c-4eeb-a55a-f4aedc495e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;transactionDateEnd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;transactionDateEnd&quot;]</value>
      <webElementGuid>ec1d8f40-d882-4a9d-9406-9e6e8a32644f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
