<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_officeName</name>
   <tag></tag>
   <elementGuidId>58cd2151-8692-4af2-81e3-02e32395b19c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>4c609024-670e-4407-a0a3-ec15f2662bc2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
