<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_tipedokumen</name>
   <tag></tag>
   <elementGuidId>4f3bf6ad-690a-47e2-8997-3046d34c305f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentType&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>d923baa6-8c1e-4d38-947a-6c5c49562e76</webElementGuid>
   </webElementProperties>
</WebElementEntity>
