<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_melanjutkan</name>
   <tag></tag>
   <elementGuidId>ced0c8c5-4e4b-4069-97e1-664d244b505c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;footerAlertR&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;footerAlertR&quot;]/button</value>
      <webElementGuid>51e70778-3745-4a41-9f63-23a42ab0d3eb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
