<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_menyetujui</name>
   <tag></tag>
   <elementGuidId>d56b7186-abcb-4cd2-a434-26c009510117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;checkme&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;checkme&quot;]</value>
      <webElementGuid>4030e479-4e8f-4d21-a717-47761ad3b49a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
