<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closePopupGagal</name>
   <tag></tag>
   <elementGuidId>13dde5cd-5009-4fa8-8b37-e4bede2a8163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;footerAlert&quot;]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;footerAlert&quot;]/button</value>
      <webElementGuid>689647f0-707c-4737-a154-df92f57b8e3c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
