<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_requestOtp</name>
   <tag></tag>
   <elementGuidId>9d582203-028a-49e7-85fa-a704f93a406f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;reqOtp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;reqOtp&quot;]</value>
      <webElementGuid>272db499-a2f7-4f03-8b49-b71db9368946</webElementGuid>
   </webElementProperties>
</WebElementEntity>
