<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_setuju</name>
   <tag></tag>
   <elementGuidId>c4501433-0a02-4cae-a6e4-2379f7293cf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;setuju&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;setuju&quot;]</value>
      <webElementGuid>5021091a-097f-460a-97ea-84d6361fd596</webElementGuid>
   </webElementProperties>
</WebElementEntity>
