<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_popupAfterProcess</name>
   <tag></tag>
   <elementGuidId>14817399-442e-49e4-93fb-da74da6f0d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;titleAlertR&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;titleAlertR&quot;]</value>
      <webElementGuid>15628af9-ab28-4eb2-a0e7-97cdbbfc64c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
