<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_success</name>
   <tag></tag>
   <elementGuidId>a3825ed4-d48d-4e2c-8e3e-809eadd3a82e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'pull-left']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pull-left</value>
      <webElementGuid>cde07818-2f70-49ce-bbe7-28c34512a90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;textAlertR&quot;]</value>
      <webElementGuid>8f3b39fe-abbe-435f-8270-b64332fb027f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
