<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_AlertProcess</name>
   <tag></tag>
   <elementGuidId>aa25762f-fd94-433b-a63a-4282679ef061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;titleAlert&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;titleAlert&quot;]</value>
      <webElementGuid>1844420b-0078-4c69-8b59-07d767ace42e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
