<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_documentId</name>
   <tag></tag>
   <elementGuidId>e36e212e-c4fb-46fd-827c-100081d4f76c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;navtop&quot;]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;navtop&quot;]/a</value>
      <webElementGuid>4f2d7e6c-0257-4e80-a3fd-0648a7f949c5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
