<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_alasanPopupGagal</name>
   <tag></tag>
   <elementGuidId>818cb98f-8b02-4da3-9978-2992e57ea863</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'textAlert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>textAlert</value>
      <webElementGuid>e4e0b75f-11a6-4863-9bca-79bf6c7a68f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;textAlert&quot;]/text()</value>
      <webElementGuid>93c5a526-847d-40a9-86b9-811f4e7bb8e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>d30cf85d-956f-4117-8ca1-8a9df31edf56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>style</name>
      <type>Main</type>
      <value>max-height: 378px; overflow-y: auto;</value>
      <webElementGuid>38ad4590-d1c3-4377-ae60-e25c3195bfdb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
