<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Embed</name>
   <tag></tag>
   <elementGuidId>a9cf1d29-23cb-4478-a600-2e10ff5d8672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/button</value>
      <webElementGuid>a36abbc3-26c1-4b44-b45f-f79fc9c448c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
