<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Embed</name>
   <tag></tag>
   <elementGuidId>a9cf1d29-23cb-4478-a600-2e10ff5d8672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'tombol']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/button</value>
      <webElementGuid>11a74284-2e10-41d2-be20-89ec18f9e60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tombol</value>
      <webElementGuid>a9549d38-4620-4b87-a05b-34acfb690e27</webElementGuid>
   </webElementProperties>
</WebElementEntity>
