<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrameEsign</name>
   <tag></tag>
   <elementGuidId>e64085c8-9a56-42ff-a48b-76d8829fb0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/div/iframe</value>
      <webElementGuid>b525a6da-7e16-4fef-bc76-2b3dc5dfc7f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
