<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputLinkEmbed</name>
   <tag></tag>
   <elementGuidId>f6ab72e7-4b66-4988-851e-43ae6bf26e98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-content-layout/div/div/div/div[2]/app-page-dummy/div/input</value>
      <webElementGuid>686f09bf-e92c-440d-bc21-7c54c2dc5d39</webElementGuid>
   </webElementProperties>
</WebElementEntity>
