<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>c4efa5a5-c3b9-441a-9917-4970557063b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;login&quot;]/div/div[2]/div/form/div[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;login&quot;]/div/div[2]/div/form/div[1]/div/input</value>
      <webElementGuid>88205b36-8890-46e5-b08e-94ac62ccf8b4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
