<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Request Link Email UAT</name>
   <tag></tag>
   <elementGuidId>782d0fda-9a11-45b6-a394-795c705bf6b0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;tenantCode\&quot;: \&quot;WOMF\&quot;,\r\n    \&quot;users\&quot;: [\r\n        {\r\n            \&quot;nama\&quot;: \&quot;ANDY\&quot;,\r\n            \&quot;email\&quot;: \&quot;${email_address}\&quot;,\r\n            \&quot;vendorCode\&quot;: \&quot;TKNAJ\&quot;\r\n        }\r\n    ],\r\n    \&quot;audit\&quot;: {\r\n        \&quot;callerId\&quot;: \&quot;MANUAL\&quot;\r\n    }\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>39ff6adb-b4e7-4dbd-a0c1-ac651da2dffa</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-api-key</name>
      <type>Main</type>
      <value>ASDFGH@WOMF</value>
      <webElementGuid>17c90b5e-fc18-42e5-9506-825ebfee4cc4</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>9.0.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${uat_url}/services/user/generateInvitationLinkV2</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.uat_url</defaultValue>
      <description></description>
      <id>991de7e1-1f8f-445b-a6ca-7b17a695dfea</id>
      <masked>false</masked>
      <name>uat_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.email_address</defaultValue>
      <description></description>
      <id>6fd71f49-59a3-4a8f-afff-e13893c75c18</id>
      <masked>false</masked>
      <name>email_address</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
