<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cari</name>
   <tag></tag>
   <elementGuidId>9b353c47-994c-4c59-b2a5-938b64f71cbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[3]</value>
      <webElementGuid>c079c8f9-8525-48b7-b685-97d0eb94b37a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
