<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SetUlang</name>
   <tag></tag>
   <elementGuidId>fa93c99d-3ff6-47de-a303-067a50ded0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[2]</value>
      <webElementGuid>6ee01f1b-adcb-47c2-be34-aab61fc3869f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
