<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_UnduhExcel</name>
   <tag></tag>
   <elementGuidId>7206fd57-b952-44af-9562-fb604596ba34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[1]</value>
      <webElementGuid>43e8014c-0084-409c-a189-6b8c5ae5435d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
