<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cabang</name>
   <tag></tag>
   <elementGuidId>879e059e-6a50-41e5-89bf-5ed02f1b64ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>32b05821-df14-45d2-994e-91828a27b4b8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
