<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalDari</name>
   <tag></tag>
   <elementGuidId>c4dcf346-69d8-4e55-81f3-4e725e21ba9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tanggalDari&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tanggalDari&quot;]</value>
      <webElementGuid>a059213c-55eb-46d0-82e4-771b5154503c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
