<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentNo</name>
   <tag></tag>
   <elementGuidId>4fc13903-621b-480f-a37d-e35b05690397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentNo</value>
      <webElementGuid>1f8287f0-4629-4943-a868-cd158a72dc44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentNo']</value>
      <webElementGuid>fcb1ed94-5d7f-4588-9e98-0557ebc5ff43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vForm']/div/div/app-text/fieldset/div/input</value>
      <webElementGuid>b0ffcc7f-e2f0-4e91-b001-4f1560c49dd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e9b61151-1bc2-4dd0-b280-a88e62c6af08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentNo' and @placeholder = 'Type document number here']</value>
      <webElementGuid>e28febfe-1790-4f59-a5fe-996cc8f2a55e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
