<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_docType</name>
   <tag></tag>
   <elementGuidId>d2adf16c-217e-48fd-86af-0ef718831198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-select-container.ng-has-value</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentType&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='documentType']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>1a8ae140-8e39-4180-9594-eeebe9ad39fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='documentType']/div</value>
      <webElementGuid>e377da60-b0d7-4310-9802-606fe989f849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[1]</value>
      <webElementGuid>e62b5bce-e45b-4150-bd25-c7476c060736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div</value>
      <webElementGuid>b37e579b-ee37-46e5-a75b-c9b2f2faa1ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih tipe dokumen×All×' or . = 'Pilih tipe dokumen×All×')]</value>
      <webElementGuid>f5c41c9d-92a1-4677-9319-3163bc929067</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
