<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentName</name>
   <tag></tag>
   <elementGuidId>a85f8b3e-f2a2-4a8f-8f49-e88ff27bc1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>63b17f04-ba89-49c9-b9cd-4aba4901aae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>bd7bebe5-c40a-4b79-a7e9-ac708cc775b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vForm']/div[2]/div/app-text/fieldset/div/input</value>
      <webElementGuid>e56834fb-0f9b-482d-95dc-8456d1de117e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/app-text/fieldset/div/input</value>
      <webElementGuid>27c098dd-84a4-4a9d-94ca-2c7df42dad11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Tulis nama dokumen']</value>
      <webElementGuid>9767147e-037b-4488-97c0-4fcf62f40b60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
