<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentExample</name>
   <tag></tag>
   <elementGuidId>4cc38095-e7e3-4442-8071-4eb9ec1f0132</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentExample</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentExample']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentExample</value>
      <webElementGuid>684e80ec-6745-4323-a439-8c7136590af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentExample']</value>
      <webElementGuid>0494e299-af02-46f5-9790-773cc1987e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vForm']/div[6]/div/app-file/fieldset/input</value>
      <webElementGuid>c57d73a3-2bda-4a6e-8142-3fa9771da016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>ebfbde17-fd04-4ec4-843b-2a44c4b3c481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'documentExample' and @placeholder = 'Pilih Dokumen']</value>
      <webElementGuid>adb2de3a-ced7-4527-afeb-ceb0810a1914</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
