<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentDate</name>
   <tag></tag>
   <elementGuidId>90aafbd5-a705-49e9-aefb-74294ed9b16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentDate</value>
      <webElementGuid>1b112d2c-2c62-4764-8f19-d9d2e3c8d2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentDate']</value>
      <webElementGuid>30fcbe50-f0e9-4fd0-83be-5aaf35ef2719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='vForm']/div[3]/div/app-date/fieldset/div/input</value>
      <webElementGuid>c6aaa5e2-1fe1-48b4-9520-2a0257ebe7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>7f0dcba6-aebb-4373-b62f-183718f51d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>a260b393-fdcf-403e-a845-ede39111f2ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
