<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_docTypePeruri</name>
   <tag></tag>
   <elementGuidId>8b8fef16-9e56-4d0b-be4e-ee02a8486725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentTypePeruri > div.ng-select-container.ng-has-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='documentTypePeruri']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentTypePeruri</value>
      <webElementGuid>d06214da-6124-456a-90b9-4bc7ea59afeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='documentTypePeruri']/div</value>
      <webElementGuid>a6eec018-7321-45e7-aa2a-59176cacce07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[1]</value>
      <webElementGuid>804dd059-0b8d-4c39-877f-2fa12fe9da33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/app-select/div/ng-select/div</value>
      <webElementGuid>c7d023f0-ed15-42ed-927a-7ee2c9a61a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Document Type Peruri×All×' or . = 'Select Document Type Peruri×All×')]</value>
      <webElementGuid>dc28c47e-c2bf-4adf-9020-23d672f07c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
