<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_docTypePeruri</name>
   <tag></tag>
   <elementGuidId>8b8fef16-9e56-4d0b-be4e-ee02a8486725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentTypePeruri > div.ng-select-container.ng-has-value</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentTypePeruri&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='documentTypePeruri']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentTypePeruri&quot;]/div/div/div[3]/input</value>
      <webElementGuid>d546a6ab-7068-48e2-aeea-47fde0616696</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='documentTypePeruri']/div</value>
      <webElementGuid>b1635fcc-aab0-4041-9c6e-f0fc854fdafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::div[1]</value>
      <webElementGuid>4da44581-b00e-4fee-bfe9-54a2f6a5342d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/app-select/div/ng-select/div</value>
      <webElementGuid>fa9758f6-4b0b-49e2-a817-b032ee0bf1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Document Type Peruri×All×' or . = 'Select Document Type Peruri×All×')]</value>
      <webElementGuid>f050e8de-4dc1-4583-93da-3af4783f1993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
