<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>af14dde1-1cb7-4a3a-994c-b650a7e25274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-stampduty-error/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-body</value>
      <webElementGuid>a22e1d5b-ea87-4d06-94e6-0b06033e6a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-stampduty-error/div/div/p</value>
      <webElementGuid>c8604f7a-950c-42e0-8e2f-e9a36712286e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
