<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalDokumenSampai</name>
   <tag></tag>
   <elementGuidId>759d841d-e888-4c9b-8cc7-6d2170cf0150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tanggalDokumenSampai']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tanggalDokumenSampai</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tanggalDokumenSampai&quot;)</value>
      <webElementGuid>5de3e242-3cd1-4542-a3a5-178b39989bf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tanggalDokumenSampai']</value>
      <webElementGuid>8d8ad7fd-42eb-4d72-88f3-22ce2abfa4c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>7ff935a9-6231-483e-a289-829c98ee4a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>7f69116b-9619-4a16-b6e3-387b2fd3208a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'tanggalDokumenSampai' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>be9783fc-de95-4c3c-9a19-676aa463abaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
