<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PengaturanDokumen</name>
   <tag></tag>
   <elementGuidId>f946200e-a385-44d7-bd6d-69b58be633d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='templateDokumen']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;templateDokumen&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#templateDokumen > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;templateDokumen&quot;]/div/div/div[3]/input</value>
      <webElementGuid>e8f4f571-077b-400b-84a8-446c375fd590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='templateDokumen']/div</value>
      <webElementGuid>edfcd4c6-b11b-4ef6-aaea-2693018206a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Dokumen'])[1]/following::div[2]</value>
      <webElementGuid>2fa2b685-e93a-4b49-820a-ffc28f7d3f75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih tipe dokumen'])[1]/following::div[6]</value>
      <webElementGuid>4b26f561-ac39-4151-a208-7ba4c250d236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>9add32f1-4748-4d4d-aabc-11ec99dda54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih template dokumen×All×' or . = 'Pilih template dokumen×All×')]</value>
      <webElementGuid>58c0ec7b-13c8-4f1b-b1ee-be70eee8408b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
