<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HasilStamping</name>
   <tag></tag>
   <elementGuidId>b4aa0a74-8ef0-40fc-82ff-cddd0ffdf88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='hasilStamping']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;hasilStamping&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hasilStamping > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;hasilStamping&quot;]/div/div/div[3]/input</value>
      <webElementGuid>7d756197-d6f2-4bc8-8241-72e13dec5832</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='hasilStamping']/div</value>
      <webElementGuid>be6440ef-4d36-4e07-af5f-c6e7fa7accd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Stamping'])[1]/following::div[2]</value>
      <webElementGuid>4b6b4126-9952-48bf-80b2-b9b5773a83f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Dokumen Sampai'])[1]/following::div[9]</value>
      <webElementGuid>5a317cb9-5003-4473-a695-3c8c7a2d0cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>a48e2776-a668-4e5e-8342-85113b8864f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih hasil stamping×All×' or . = 'Pilih hasil stamping×All×')]</value>
      <webElementGuid>db501f03-e1e9-42de-a7eb-386830ddf190</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
