<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_JenisPajak</name>
   <tag></tag>
   <elementGuidId>ed52d0e7-1ddc-47a0-8e3c-975e4409ef44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='taxType']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;taxType&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#taxType > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;taxType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>e243c0bc-6bf8-4688-91cc-d26a2edb9ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='taxType']/div</value>
      <webElementGuid>e89b3986-f395-48bb-8e17-af921de97a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Pajak'])[1]/following::div[2]</value>
      <webElementGuid>32d52a25-1664-4feb-aeeb-bbf9fe52c30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[4]/following::div[6]</value>
      <webElementGuid>a1a8dbd0-6644-4387-a783-8fc60b115ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>64b89be7-b476-4e63-989b-b263801c2322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select tax type×All×' or . = 'Select tax type×All×')]</value>
      <webElementGuid>ef4d3650-47a2-4ca4-bc92-9becc643b3cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
