<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_HasilStamping</name>
   <tag></tag>
   <elementGuidId>b4aa0a74-8ef0-40fc-82ff-cddd0ffdf88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='hasilStamping']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hasilStamping > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hasilStamping&quot;)</value>
      <webElementGuid>567de0f9-ce06-411c-98d3-038fe13c3196</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='hasilStamping']/div</value>
      <webElementGuid>5f333c13-9bb8-4b6c-909c-0f19433e35ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hasil Stamping'])[1]/following::div[2]</value>
      <webElementGuid>fd37a5ee-7cc1-4d52-998d-47d483339604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal Dokumen Sampai'])[1]/following::div[9]</value>
      <webElementGuid>f2912726-7b9f-437c-a806-52616d170793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>3c85fbb4-4bd4-4e20-95a0-597e3d873974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih hasil stamping×All×' or . = 'Pilih hasil stamping×All×')]</value>
      <webElementGuid>74feced3-a030-4528-8fc9-60fefd6e2f60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
