<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PengaturanDokumen</name>
   <tag></tag>
   <elementGuidId>f946200e-a385-44d7-bd6d-69b58be633d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='templateDokumen']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#templateDokumen > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;templateDokumen&quot;)</value>
      <webElementGuid>05c18fb3-c7a9-4e76-9895-ebf0f45429e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='templateDokumen']/div</value>
      <webElementGuid>766f3bd1-fbd0-47e7-8ade-ed85151de82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Dokumen'])[1]/following::div[2]</value>
      <webElementGuid>a491660e-02f8-4def-9873-de9b45c9835f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih tipe dokumen'])[1]/following::div[6]</value>
      <webElementGuid>e92e9293-9aba-445a-81c3-e310717b5a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>24e1e378-6656-47a0-8952-a56ce4424bb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih template dokumen×All×' or . = 'Pilih template dokumen×All×')]</value>
      <webElementGuid>3a51e29d-d3d0-4d60-b4e1-16f708a571ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
