<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cabang</name>
   <tag></tag>
   <elementGuidId>884b077d-cdfc-467b-8555-501cc02e7f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='cabang']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;cabang&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cabang > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;cabang&quot;]/div/div/div[3]/input</value>
      <webElementGuid>06c19aa4-99df-49e4-948f-02f33d85bd39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='cabang']/div</value>
      <webElementGuid>62866769-b203-4a82-90cd-31df266030fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::div[2]</value>
      <webElementGuid>1b6a3bc9-c426-4af4-9ddb-bd7d3cf8e5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Seri'])[1]/following::div[7]</value>
      <webElementGuid>75e0a117-5110-4335-9fee-ef6f629774c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>737abdc6-e532-4284-9c01-1173516d36bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select office×All×' or . = 'Select office×All×')]</value>
      <webElementGuid>d7badeac-3857-4dbf-aab1-1e26e4b9f336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
