<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cabang</name>
   <tag></tag>
   <elementGuidId>884b077d-cdfc-467b-8555-501cc02e7f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='cabang']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cabang > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cabang&quot;)</value>
      <webElementGuid>33cba7d9-226d-4434-b206-5e5635ea0769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='cabang']/div</value>
      <webElementGuid>6c395de5-099f-4b96-90da-851b5b0874a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang'])[1]/following::div[2]</value>
      <webElementGuid>0255ee8d-5a8b-43f8-b316-bc8640efb03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Seri'])[1]/following::div[7]</value>
      <webElementGuid>2f1a38ed-65ef-4bf6-bfef-8c04ef0062ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>440bc548-8ed3-4c76-8146-e34e4dfd9bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select office×All×' or . = 'Select office×All×')]</value>
      <webElementGuid>53023e62-16de-4a53-9242-f1c10df3a176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
