<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tipe Dokumen</name>
   <tag></tag>
   <elementGuidId>e652bbf3-f8bd-403c-b184-f78f42ba627a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='tipeDokumen']/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tipeDokumen&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipeDokumen > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tipeDokumen&quot;]/div/div/div[3]/input</value>
      <webElementGuid>6e4c6283-86e0-4513-8782-799247d89331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='tipeDokumen']/div</value>
      <webElementGuid>e5bc5b11-16d6-4ac6-9e76-a8775f75bae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipe Dokumen'])[1]/following::div[2]</value>
      <webElementGuid>79eb7ebb-61d5-4054-ab06-9fd6b259c6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/following::div[6]</value>
      <webElementGuid>5452827d-8182-498e-bac0-30f02a022b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>9d66b7a4-2d98-4946-a57f-9e93ac315ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih tipe dokumen×All×' or . = 'Pilih tipe dokumen×All×')]</value>
      <webElementGuid>cadc71c0-020d-43f8-8694-69a7a2a13f53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
