<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Proses</name>
   <tag></tag>
   <elementGuidId>cccf54d6-368b-4042-a31a-48cadc53bfb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prosesSign</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='prosesSign']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c3cedc54-dbd6-4632-b121-d7aa649c4e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prosesSign</value>
      <webElementGuid>42f6c2b8-dc6c-44bd-9c78-7e1f87217a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success block</value>
      <webElementGuid>75b53337-1155-4332-956f-fb7e32bd0390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Proses</value>
      <webElementGuid>9d39d783-b3b2-43ca-809d-a2d3d684896d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prosesSign&quot;)</value>
      <webElementGuid>4354cde4-88bf-48a4-ac3a-cad62d134809</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='prosesSign']</value>
      <webElementGuid>e9937a54-a9b7-440b-8b9d-832a51b5f8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbottom']/button</value>
      <webElementGuid>01247d27-a6f0-4838-b4c0-646ae0027678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::button[1]</value>
      <webElementGuid>0b05eca0-5bdd-45ad-8565-b70d09eeb619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/following::button[2]</value>
      <webElementGuid>f7e7aad3-621b-4bdf-a1f1-2b528f5ffe15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='powered by :'])[1]/preceding::button[1]</value>
      <webElementGuid>67cc05f9-dadb-45cf-a919-38e56125b33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::button[1]</value>
      <webElementGuid>864e73a7-551f-4a7b-97fa-67316ade9b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/button</value>
      <webElementGuid>58d0c310-1be1-4798-828b-2744d73ca23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'prosesSign' and (text() = 'Proses' or . = 'Proses')]</value>
      <webElementGuid>e8c2e4fd-f354-42a3-847b-207c24d1bb53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
