<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_pdfprev</name>
   <tag></tag>
   <elementGuidId>49fd6f9a-8a22-49ab-a51a-95c531828168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pdf-prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pdf-prev']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf534cef-10c7-4d70-83b8-0297518588c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-circle</value>
      <webElementGuid>6c7cff07-16c1-4754-a12a-b44f401fee46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pdf-prev</value>
      <webElementGuid>1a3fe124-7672-4eeb-959d-0ebb4efa4249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> &lt; </value>
      <webElementGuid>ce7f18bf-5064-4b74-ad04-895abcd66e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pdf-prev&quot;)</value>
      <webElementGuid>c51f7dca-89f3-43fb-bc93-89a4a7ca219a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pdf-prev']</value>
      <webElementGuid>cdb02e15-6787-43c2-97a2-23564ea6b734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>83da90b6-decd-43ee-a994-aef296b7cb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::button[2]</value>
      <webElementGuid>d3b356dc-bc54-409c-9905-dcef8746917c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::button[1]</value>
      <webElementGuid>472b2684-c14f-40ac-8df6-8dfe8c7f90de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/preceding::button[2]</value>
      <webElementGuid>c8bb1946-c38a-4bea-affc-10bc88916ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&lt;']/parent::*</value>
      <webElementGuid>0c9a641b-f4ee-4f8a-90ba-f45455b07365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>a3835ac4-5b74-4ae7-aeca-afe34b2d4521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pdf-prev' and (text() = ' &lt; ' or . = ' &lt; ')]</value>
      <webElementGuid>836b7f5d-869b-42ce-8826-525d63338522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
