<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SignClick</name>
   <tag></tag>
   <elementGuidId>41fc3df6-8657-4ddb-9fb5-c3f936328ad3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sgnClick-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sgnClick-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d45d951-0ea5-41ea-9b1d-a535f7ee8553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>41bee06f-f49f-4671-937b-d1979d4e7fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sgnClick-0</value>
      <webElementGuid>7b993dbd-7a6f-48a1-b5bf-f46bd5f7c8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>eb4d2679-514d-4c9d-9df4-f6b91671d446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>signProcess(0);</value>
      <webElementGuid>46b4f83a-b486-4a7a-8ee8-49d87a9576c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sgnClick-0&quot;)</value>
      <webElementGuid>a9eb5261-c5aa-4b12-adc0-cb97be8f8acc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sgnClick-0']</value>
      <webElementGuid>2b8e1fca-c295-4f7f-83cc-8ffa6aecdc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sgn-user-0']/a</value>
      <webElementGuid>c7071c67-21af-4705-83e3-691bba4bd429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/following::a[1]</value>
      <webElementGuid>97308b4c-a1c6-46b0-98c3-5f10dbf4e1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/following::a[2]</value>
      <webElementGuid>0ca34932-ce63-4e04-b3db-c3a6836d1033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Page'])[1]/preceding::a[1]</value>
      <webElementGuid>a1008514-43c0-438b-a2cf-5b7002ab93fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>260cc43e-da0f-4c41-aba5-740ca4feff5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>6e9bdbe1-68c5-42f6-be1b-fd9038e94299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sgnClick-0' and @href = 'javascript:void(0)']</value>
      <webElementGuid>6257d93c-35e1-498a-9df8-43dff9cb0c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
