<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_clickSign</name>
   <tag></tag>
   <elementGuidId>03ae4d4d-5f5e-4374-a88e-6b1f0d18a69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sgn-user-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;sgn-user-0&quot;)[count(. | //div[@id = 'sgn-user-0' and @class = 'sign-box']) = count(//div[@id = 'sgn-user-0' and @class = 'sign-box'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sgn-user-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8367a6e8-78af-4754-bff3-82badbc17ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sgn-user-0</value>
      <webElementGuid>dbc28c66-19b5-4275-8418-a0cf85769993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-box</value>
      <webElementGuid>6d67aef6-eea1-42e4-a4a1-14227a3adc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sgn-user-0&quot;)</value>
      <webElementGuid>203ba7db-717e-42aa-abc9-265992205b63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sgn-user-0']</value>
      <webElementGuid>776ea8f7-e4fe-4889-9cde-12075b775e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sgn-widget']/div</value>
      <webElementGuid>0dff305a-b808-44f0-bfdb-9fc418422e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/following::div[2]</value>
      <webElementGuid>6e932bbe-0219-4a74-889d-3be83db4a7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/following::div[7]</value>
      <webElementGuid>6afa68f2-1b13-41ec-af6b-36b34ddf3e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Page'])[1]/preceding::div[2]</value>
      <webElementGuid>200caa3a-5d24-4bde-90dc-64f21bb48aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div</value>
      <webElementGuid>2d72a861-e6c7-456b-9584-0f059e76c61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sgn-user-0']</value>
      <webElementGuid>61eb3000-a9da-4e96-871d-bedc82ea9b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
