<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_runtotalPage</name>
   <tag></tag>
   <elementGuidId>a44750d4-084f-4916-919e-93a9705179ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goEnter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='goEnter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24aba46d-62a6-482d-bb85-d28bccf4e0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b9245a96-ae38-4a8b-acd2-25dea8195365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goEnter</value>
      <webElementGuid>d10e0353-94b0-4ae3-b04c-b13f339e36fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mb-2 mr-sm-2</value>
      <webElementGuid>955b277e-3f9f-4e89-9932-3d82a21ed07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>63335182-eaa0-47c6-be16-329ce9ef6914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GO</value>
      <webElementGuid>849108dd-4b64-459f-82b6-1164e9c5fe8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goEnter&quot;)</value>
      <webElementGuid>22e9b31e-3791-4daf-959b-62659621f1db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='goEnter']</value>
      <webElementGuid>d0d76a9e-ce48-40b8-a5fd-f336cc7b115b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='footerAlert']/button)[2]</value>
      <webElementGuid>7f9024e6-3178-44a6-a590-824557bdb8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to page :'])[1]/following::button[1]</value>
      <webElementGuid>70dde3dd-2517-4d33-a679-db8e6add2175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tekan Disini Untuk Melanjutkan'])[1]/following::button[1]</value>
      <webElementGuid>117f6cea-402b-4ce9-87a3-dd200d9ef149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Info'])[1]/preceding::button[1]</value>
      <webElementGuid>a32ec715-2030-49c6-9c93-80903e995ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Sudah ditandatangan'])[1]/preceding::button[1]</value>
      <webElementGuid>72d3fa99-2fb6-4146-844d-91a47cc0980c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GO']/parent::*</value>
      <webElementGuid>ed85989e-8099-4652-bd14-3931bfff507c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button</value>
      <webElementGuid>219cb24d-b904-4373-9c07-77bb4f71320b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'goEnter' and (text() = 'GO' or . = 'GO')]</value>
      <webElementGuid>c8e8a8c8-475a-417a-b6ab-a7d78418b43b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
