<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_totalPage</name>
   <tag></tag>
   <elementGuidId>8d09467a-fe34-4de8-8a98-186f0f20dc96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goButton</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'goButton']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='goButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0c1c466-04d3-4717-ad20-0039ffaea5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goButton</value>
      <webElementGuid>cf567712-8349-4267-b204-99071ae1a0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-circle2</value>
      <webElementGuid>28b66f0f-2c19-406d-9d91-06ece2a8f408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>41/42</value>
      <webElementGuid>29842206-c39f-462e-b99b-d2e22e50612b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)</value>
      <webElementGuid>67f62ff2-0349-4c7c-84c6-18a093c673fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='goButton']</value>
      <webElementGuid>4855d30c-c5d9-47a5-924a-7443fcca7410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Page'])[1]/following::button[1]</value>
      <webElementGuid>2e689765-d0d8-4fdb-a4de-d3c2ab461ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/following::button[2]</value>
      <webElementGuid>caecc8e8-0f19-4196-8301-6c0f0e0dfcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::button[1]</value>
      <webElementGuid>628c653d-d9e1-4891-96c5-471a784096a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/preceding::button[2]</value>
      <webElementGuid>e3ed30f4-683c-43c2-aac3-8f7a927b49d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/']/parent::*</value>
      <webElementGuid>945433c9-b83b-462f-bc54-600128494678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/button</value>
      <webElementGuid>068db21f-404a-48ba-93f4-2a678f2d3679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'goButton' and (text() = '41/42' or . = '41/42')]</value>
      <webElementGuid>32e4ba99-c57e-40b2-b7a1-4389c501d43a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
