<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nav Doc</name>
   <tag></tag>
   <elementGuidId>2002b77e-ef42-4bf0-ace9-be1d28067e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;navtop&quot;)/a[@class=&quot;navbar-brand&quot;][count(. | //a[@class = 'navbar-brand' and @href = '#']) = count(//a[@class = 'navbar-brand' and @href = '#'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navtop']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42bb0d5b-4333-470e-9846-bf229d2063a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>7b58623e-036e-4722-9ecf-35db211fbcea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>da4de84b-e0f6-4bb7-b3e2-b4508c1ec566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOC_00155D0B-7502-9AC7-11ED-C78DBFC24710.pdf</value>
      <webElementGuid>ba1d8c4c-ee65-4f9e-8956-5d62005c1484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navtop&quot;)/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>b085b7b9-a584-4999-ad75-be30f13ae6d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navtop']/a</value>
      <webElementGuid>e9790e9f-5a5d-41bc-9b3b-0065edb21ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DOC_00155D0B-7502-9AC7-11ED-C78DBFC24710.pdf')]</value>
      <webElementGuid>84db9932-89e0-4fac-b172-0bd6ffcf672c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/following::a[1]</value>
      <webElementGuid>5588820a-e351-462d-91e0-6c073283d383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setuju'])[1]/following::a[1]</value>
      <webElementGuid>267480c8-b5e9-4f13-a6a0-3925bdf01845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading page ...'])[1]/preceding::a[1]</value>
      <webElementGuid>9542a71a-e68e-44d9-95cc-20ef79a2cbb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Page'])[1]/preceding::a[2]</value>
      <webElementGuid>29c70c3d-54c7-4616-94bf-c4ae1c92290a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DOC_00155D0B-7502-9AC7-11ED-C78DBFC24710.pdf']/parent::*</value>
      <webElementGuid>ea4c4267-f88c-4b7d-8908-892b72402cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>aad086bc-090a-4bcc-ba70-f51567690e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>a3949713-c62e-470b-9d86-c0859d858153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'DOC_00155D0B-7502-9AC7-11ED-C78DBFC24710.pdf' or . = 'DOC_00155D0B-7502-9AC7-11ED-C78DBFC24710.pdf')]</value>
      <webElementGuid>c97cfa2d-0005-4d16-a3a3-4679c6818fbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
