<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_X</name>
   <tag></tag>
   <elementGuidId>80aba926-bef1-4886-86f7-a851299718dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-signer/div[1]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-signer/div[1]/button/span</value>
      <webElementGuid>94a0c0c2-3f21-4e52-813a-8be361eb2ab9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
