<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPermintaanSampai</name>
   <tag></tag>
   <elementGuidId>7e54c75c-3d11-430c-8681-e79e289650d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;requestedDateEnd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;requestedDateEnd&quot;]</value>
      <webElementGuid>98e80b67-26b7-4fef-a3cf-653285c233f6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
