<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalSelesaiDari</name>
   <tag></tag>
   <elementGuidId>5a23860c-35f4-4f65-a068-ad8570222670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;completedDateStart&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;completedDateStart&quot;]</value>
      <webElementGuid>1d8e7edd-8bed-486d-a9dc-347bcbfdb9dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
