<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TipeDokumen</name>
   <tag></tag>
   <elementGuidId>dac7390d-657a-406b-9c46-e2697befca60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;docType&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;docType&quot;]/div/div/div[3]/input</value>
      <webElementGuid>93d21f4d-8db4-44f5-b957-125b11d65424</webElementGuid>
   </webElementProperties>
</WebElementEntity>
