<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_DDLPembayaranTTD</name>
   <tag></tag>
   <elementGuidId>5a1565a1-4264-4955-8acc-5700aeb8b292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentSignTypeCode&quot;]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentSignTypeCode&quot;]/div/span[2]</value>
      <webElementGuid>a12fcb4b-987d-4b15-a326-7051282ada3e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
