<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_tipetandatangan</name>
   <tag></tag>
   <elementGuidId>aa633c4d-af49-498b-832d-ad5cb7b73437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'signerType']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;signerType&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signerType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3ab0ef96-700d-458e-8bd3-b5776a8e3b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signerType</value>
      <webElementGuid>936a49ab-8f08-42ae-a714-57bdb059457f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>2285ec3d-2c18-4f67-9eb8-a0fead1df624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>GRT</value>
      <webElementGuid>8b77567e-9ee5-4720-a708-5544a5ab14b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Guarantor  Supplier  Employee  Spouse  Customer </value>
      <webElementGuid>05f1a7b7-188e-4070-8fd6-d2ab190ff3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;signerType&quot;]</value>
      <webElementGuid>9d4df1dd-f469-44a9-9e52-5df513b2cf1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='signerType']</value>
      <webElementGuid>84cf48ae-c925-4bb3-9445-7a0cc92d6f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Tipe Tanda Tangan'])[1]/following::select[1]</value>
      <webElementGuid>239137a9-9031-4673-b98c-72e5618bc4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'signerType', '&quot;', ')')])[1]/following::select[1]</value>
      <webElementGuid>1a49aef7-96e7-4a0d-936e-6aa3ba7fd482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set Signer'])[1]/preceding::select[1]</value>
      <webElementGuid>94fa0a60-1368-468d-820b-c1c251c6d65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>4c8d4075-fdb8-4a16-9845-f35a08b34ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'signerType' and (text() = ' Guarantor  Supplier  Employee  Spouse  Customer ' or . = ' Guarantor  Supplier  Employee  Spouse  Customer ')]</value>
      <webElementGuid>9e2ae284-32cc-41f2-aef5-8a6e3e9bd386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
