<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_tipepembayaran</name>
   <tag></tag>
   <elementGuidId>6e85da77-a082-49e1-941e-0aaab5d52e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;af50b7139255&quot;]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#a84ba5e6f8d6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ng-dropdown-panel ng-star-inserted ng-select-bottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ng-dropdown-panel</value>
      <webElementGuid>2435a3b0-7b14-45c6-b347-b9dce4bd8509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-dropdown-panel ng-star-inserted ng-select-bottom</value>
      <webElementGuid>1f425f4e-1ba2-4b3b-81dd-a5e1fc52c64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-virtual-scroll</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8983abff-6517-44c9-a4b7-4cf15ae8d634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-buffer-amount</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ecc352a5-8938-45c1-a56f-87b3b4ce6cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-position</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2c83c0b5-36d8-44ef-9176-693655ec984c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-items</name>
      <type>Main</type>
      <value>[object Object],[object Object</value>
      <webElementGuid>2a4b7cb7-8fa3-4e9a-b8c4-8b8f1edacd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-marked-item</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>a622dd0b-535f-4b33-b6bb-096406583620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>a84ba5e6f8d6</value>
      <webElementGuid>1fd73fb1-b396-4eb2-a147-08938341e42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Per DocumentPer Sign</value>
      <webElementGuid>1edfc49b-a192-4e83-977c-32539f007775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a84ba5e6f8d6&quot;)</value>
      <webElementGuid>c891f8ad-2d40-4ea4-99a2-a96e14eeaf66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='a84ba5e6f8d6']</value>
      <webElementGuid>9646c59f-252d-4c3b-86cd-5d1d386c46f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='paymentSignTypeCode']/ng-dropdown-panel</value>
      <webElementGuid>c0ea2119-7d3a-4cf0-847f-b8ff5b15c3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select payment sign type'])[1]/following::ng-dropdown-panel[1]</value>
      <webElementGuid>7071013b-3c9e-47aa-bc04-e46622308a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::ng-dropdown-panel[1]</value>
      <webElementGuid>91caebbe-8287-49c3-9ea1-a3ea1a372a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel</value>
      <webElementGuid>93b6989a-5366-46de-b9f8-eb12f1e87d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id = 'a84ba5e6f8d6' and (text() = 'Per DocumentPer Sign' or . = 'Per DocumentPer Sign')]</value>
      <webElementGuid>efbae271-072a-43e6-b902-ba8ce9246e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
