<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select payment sign type</name>
   <tag></tag>
   <elementGuidId>fb6d1923-2425-4453-8a9f-39ba8b24a539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='paymentSignTypeCode']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>799e6705-81b5-4bd9-97dc-f3305929569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-select-container ng-has-value</value>
      <webElementGuid>4fef2ca1-20cc-44ca-bf02-c48f6eaa92a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select payment sign type××</value>
      <webElementGuid>219ae068-2d78-47b8-8591-43316d1e6f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentSignTypeCode&quot;)/div[@class=&quot;ng-select-container ng-has-value&quot;]</value>
      <webElementGuid>7dcc779f-45d0-4991-8cdc-1e8b99664fdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='paymentSignTypeCode']/div</value>
      <webElementGuid>3013131e-3072-40e9-a3aa-d8bb6b0c854f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::div[1]</value>
      <webElementGuid>9b8011e2-6d22-4ef3-a2e6-6bb02d693b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div</value>
      <webElementGuid>9fc944e0-894c-47b5-a61c-814f2a81395a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select payment sign type××' or . = 'Select payment sign type××')]</value>
      <webElementGuid>e1c6cbc3-b788-48c8-b65f-7c96368f4142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
