<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status</name>
   <tag></tag>
   <elementGuidId>d6e998d2-17a4-48b3-9f8c-c7eeb7b1a261</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ng-select-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='isActive']/div&#xd;
//*[@id=&quot;isActive&quot;]/div/div/div[3]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;isActive&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f53b4e5-11f7-4f1d-be9c-f488423e6578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-select-container</value>
      <webElementGuid>37df46a3-316e-44c7-82f6-e620d45f0546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih status</value>
      <webElementGuid>65cbf485-bbe7-4d45-9615-c6d78c6d1fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isActive&quot;]/div/div/div[3]/input</value>
      <webElementGuid>fd55fe2c-4ebb-4a9c-ba42-a2764b3ad0e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='isActive']/div</value>
      <webElementGuid>65b64d36-73ec-41d6-9e54-48648410678f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::div[2]</value>
      <webElementGuid>f8096bf1-d71a-4c2c-b9d6-0df4d1262bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Templat Dokumen'])[1]/following::div[7]</value>
      <webElementGuid>340bb97a-1a20-486b-bb2d-2db9b558399d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::div[5]</value>
      <webElementGuid>5eec837c-9a03-4229-87f1-2d999609756b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-select/div</value>
      <webElementGuid>2077dc38-82a5-41d1-ad4c-51a925643fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Pilih status' or . = 'Pilih status')]</value>
      <webElementGuid>10368d3c-3a94-4124-b924-76ecdce95c5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
