<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaTemplatDokumen</name>
   <tag></tag>
   <elementGuidId>b651418a-104e-4094-941b-b955472ac4ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentTemplateName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentTemplateName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f294fb-a8cd-4d3a-9635-6cad57cbabaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2f6e2ec3-7cc0-4621-9e24-a6c90df3c31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>212a7981-f2ca-4bcc-aa0c-870255673e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentTemplateName</value>
      <webElementGuid>35c52646-76ba-43bd-a838-4588c5e9b627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentTemplateName</value>
      <webElementGuid>33bb7562-2e51-4d93-8e9c-9a178fd151d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nama templat dokumen</value>
      <webElementGuid>7c763797-58d9-41f2-8e5d-3eae68d48272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentTemplateName&quot;)</value>
      <webElementGuid>0a468195-e066-41aa-ab1e-a46df83c8293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentTemplateName']</value>
      <webElementGuid>d86a8543-6f99-4b25-b378-1c249fdd936b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>262ae019-2752-45a5-9842-558d9c622562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>8694db1f-0de4-41d6-b839-ebb0ee43f6ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentTemplateName' and @placeholder = 'Tulis nama templat dokumen']</value>
      <webElementGuid>abe40d52-7203-4cd4-8bd0-064269883aea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
