<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentTemplateName</name>
   <tag></tag>
   <elementGuidId>2fefdee2-0e85-4723-96e5-c4200b45bcd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @id = 'documentTemplateName' and @placeholder = 'Tulis nama templat dokumen']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentTemplateName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentTemplateName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5978dc3d-b6bd-4d44-aaa6-e52dee778600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1e373f13-4272-4888-bec7-5b3d81fadb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bea79b4d-ab82-456e-a4b9-918c4d1a804b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentTemplateName</value>
      <webElementGuid>92e2a714-f5a2-4a2d-b8f5-2cbd952fc0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentTemplateName</value>
      <webElementGuid>6914fed6-9479-4df3-95a4-5d56738a3c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nama templat dokumen</value>
      <webElementGuid>4f94af3a-7748-4f2d-a8c4-6d7c68e9baba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f30d846d-d772-4a89-ad02-a7bd13d909ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentTemplateName&quot;)</value>
      <webElementGuid>06156079-dbf1-4143-8413-6896c93505c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentTemplateName']</value>
      <webElementGuid>11799e1f-5231-4f01-8582-f04e18b57ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>34a35dbe-7332-4693-82fc-c08887d0074f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>9ccd2782-94c2-4fa3-8325-6d962806bf85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentTemplateName' and @placeholder = 'Tulis nama templat dokumen']</value>
      <webElementGuid>dcdad99d-3703-450a-977e-f144bb61db4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
