<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StatusAktif</name>
   <tag></tag>
   <elementGuidId>0153643c-368f-4de6-9b42-77477b1f7df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ae6f3f9e869c&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;isActive&quot;]/div/div/div[3]/input[count(. | //*[@class = 'ng-option ng-option-selected ng-option-marked ng-star-inserted']) = count(//*[@class = 'ng-option ng-option-selected ng-option-marked ng-star-inserted'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isActive > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d2a3fddf-52b5-4c03-990d-9128c75f5271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One×Active×</value>
      <webElementGuid>261a08ca-0a64-4fc9-8313-e26322f5a9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isActive&quot;]/div/div/div[3]/input</value>
      <webElementGuid>0bc54722-c872-43e7-8ea8-6adbb7698578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a813f5dffc6a</value>
      <webElementGuid>4c3a27d5-f171-4abf-b22e-35f8c193d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-option-marked ng-star-inserted</value>
      <webElementGuid>d252c9a2-7a95-4450-8273-4a48fd37d7dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='isActive']/div</value>
      <webElementGuid>ee8a88b3-a729-4d83-ba84-b697936b5c81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[1]</value>
      <webElementGuid>2d338b44-9c11-4bc4-ba67-26455675006f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/app-question/app-select/div/ng-select/div</value>
      <webElementGuid>688fff6a-0a3f-46b5-95bf-f7359b4bad07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select One×Active×' or . = 'Select One×Active×')]</value>
      <webElementGuid>d54410bd-8715-462a-af99-9760554c0e75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
