<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentExample</name>
   <tag></tag>
   <elementGuidId>9463f394-927d-48b0-b72f-b9c376fa3d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentExample']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentExample</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c864a7fb-b517-453c-a24b-83210b1c6ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>860f27e1-e4f5-423c-9265-6c6bcdff4c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ba29be56-f7b1-4bf9-9e09-4a029fad8077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentExample</value>
      <webElementGuid>68fc1eed-3eeb-476e-a93d-a199ff5cfe75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentExample</value>
      <webElementGuid>a8dd9a35-2ff9-45b4-b45b-061493e7fd03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pilih Dokumen</value>
      <webElementGuid>082a8059-dfe3-461c-b0ac-2abc3af91a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f9ca871-c6da-4192-8f36-75af4f805e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/pdf</value>
      <webElementGuid>1cea580f-7e62-40af-9d3f-2bf192b08d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentExample&quot;)</value>
      <webElementGuid>c90c6e1f-0a19-448f-81a5-c4ef200fc94c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentExample']</value>
      <webElementGuid>fa6e8082-ff57-49ad-a171-dec0fb40437c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[5]/app-question/app-file/fieldset/input</value>
      <webElementGuid>f5c2431e-68cb-4acb-94a8-92c8408afc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>baa5a686-9be8-49e3-bdd3-1989e879252f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'documentExample' and @placeholder = 'Pilih Dokumen']</value>
      <webElementGuid>1f32bed5-40d9-4b0f-97ae-9e80859264c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
