<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentTemplateDescription</name>
   <tag></tag>
   <elementGuidId>1a25abe2-ccfb-4f90-b4ca-b4bbd0fb208f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @ng-reflect-name = 'documentTemplateDescription' and @id = 'documentTemplateDescription' and @placeholder = 'Tulis deskripsi']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentTemplateDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentTemplateDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>968a3128-ba54-4b8d-bba3-1258e42d4cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c697fd91-677d-458d-8c5a-006f844d5fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8508c12b-0b5b-4a11-a90d-e6eb3f9a4603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentTemplateDescription</value>
      <webElementGuid>044060ec-e560-4999-aece-0815b6cf0deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentTemplateDescription</value>
      <webElementGuid>c5b097d6-e45f-4ed8-ba5e-f519bc266290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis deskripsi</value>
      <webElementGuid>1af874a8-d10b-4fac-9425-73e12a8d6e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b741a361-3bf0-4a80-b178-4aadef9d7f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>cd16290b-ea8d-4c32-9835-0522c4820be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentTemplateDescription&quot;)</value>
      <webElementGuid>b550d7f7-e5d9-4c47-a3c6-362484985698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentTemplateDescription']</value>
      <webElementGuid>f782a145-0bd4-42be-a0ef-9f037d60445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[3]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>56d7dfc2-1d70-4b1c-9569-460dba303196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>6aa00924-0c8c-4c79-8596-b97c3dc31b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentTemplateDescription' and @placeholder = 'Tulis deskripsi']</value>
      <webElementGuid>e6367e30-759c-428c-844d-5ebe6d574916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
