<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentTemplateDescription</name>
   <tag></tag>
   <elementGuidId>1a25abe2-ccfb-4f90-b4ca-b4bbd0fb208f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;documentTemplateDescription&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentTemplateDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentTemplateDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c41d845-5b47-42f1-8626-dad30a600e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>190569a7-2070-4779-8faf-95468085c15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f1f3169f-8b0d-4b5c-9ffe-36cba56eda54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentTemplateDescription</value>
      <webElementGuid>9f15842e-0aca-4a77-8287-492f5b65eafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentTemplateDescription</value>
      <webElementGuid>94b054de-724f-4e57-bde5-3c1da31980e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis deskripsi</value>
      <webElementGuid>e00d616d-816c-42ea-b19b-61dbd28eec91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b9004ad4-985f-4397-994b-572e4f655d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0bbf8017-a7a2-442b-9af1-8a55c9953fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentTemplateDescription&quot;)</value>
      <webElementGuid>37bf0b4a-e95c-48ca-9cf1-63e55b964216</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentTemplateDescription']</value>
      <webElementGuid>e4caa857-09e1-463f-96bf-fb79a1fa974f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[3]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>ae70aa04-ec04-4c6f-b09f-3053e7c2aa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-question/app-text/fieldset/div/input</value>
      <webElementGuid>c36c70dc-803d-4941-87d4-7b7d786e9f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentTemplateDescription' and @placeholder = 'Tulis deskripsi']</value>
      <webElementGuid>948b188a-c296-4254-80bf-c9acf34c99ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
