<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StatusAktif</name>
   <tag></tag>
   <elementGuidId>0153643c-368f-4de6-9b42-77477b1f7df6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Select One×Active×' or . = 'Select One×Active×') and @class = 'ng-option ng-option-selected ng-option-marked ng-star-inserted']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ae6f3f9e869c&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#isActive > div.ng-select-container.ng-has-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ceac7d86-a589-4d4a-bdcd-636ebda94a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select One×Active×</value>
      <webElementGuid>e229223d-8f6f-4532-b418-a2a0229579e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isActive&quot;]/div/div/div[3]/input</value>
      <webElementGuid>13f6f212-bea4-4362-9980-585e47bc6545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a813f5dffc6a</value>
      <webElementGuid>80626834-133f-46e3-942d-c06202d377d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option ng-option-selected ng-option-marked ng-star-inserted</value>
      <webElementGuid>b9324b0d-b49a-4087-ba8d-52043e496c22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='isActive']/div</value>
      <webElementGuid>8bc2c5e2-5fc3-4633-bed2-02b71fd82740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[1]</value>
      <webElementGuid>a75dd217-6558-468d-899a-60db83dc0aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/app-question/app-select/div/ng-select/div</value>
      <webElementGuid>cfdda163-3da4-4214-b24a-53326dbb66a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select One×Active×' or . = 'Select One×Active×')]</value>
      <webElementGuid>3a6197d4-17f2-4f69-8585-9ddaed6b714a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
