<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Status</name>
   <tag></tag>
   <elementGuidId>343ea98e-accb-442a-a03a-d80922f7b8ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='searchForm']/div/div[3]/app-question/app-select/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-select.ng-star-inserted > div.form-group.row.ng-pristine.ng-valid.ng-star-inserted.ng-touched > div.col-5 > label.msx-form-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4871aa69-e1c7-44a7-a389-5c37aa595341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>msx-form-label</value>
      <webElementGuid>c20cabd3-1c53-45bd-a143-7266104ed29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isActive</value>
      <webElementGuid>7349223e-7f44-402c-b0e1-16968b26b9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status </value>
      <webElementGuid>3fde4bec-7303-431a-be00-09847bc7cca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-6 ng-star-inserted&quot;]/app-question[1]/app-select[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;form-group row ng-pristine ng-valid ng-star-inserted ng-touched&quot;]/div[@class=&quot;col-5&quot;]/label[@class=&quot;msx-form-label&quot;]</value>
      <webElementGuid>65f71a1c-aca9-469b-93c0-6f701fc9b188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[3]/app-question/app-select/div/div/label</value>
      <webElementGuid>d0f82a81-769c-41b1-8b41-08016cb25110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Templat Dokumen'])[1]/following::label[1]</value>
      <webElementGuid>39338d6f-9c05-4e79-ac1c-6c14a33ce3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Templat Dokumen'])[1]/following::label[2]</value>
      <webElementGuid>86e5de97-b235-4067-ad1c-25a53bbb7515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih status'])[1]/preceding::label[1]</value>
      <webElementGuid>10ce9e74-d299-4bba-852a-5fb5b232c626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::label[1]</value>
      <webElementGuid>70c2f8f6-5390-49c1-ba29-e03f38c3df88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Status']/parent::*</value>
      <webElementGuid>7b8e0999-7be7-4a48-ba47-5ac77dc1f1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-select/div/div/label</value>
      <webElementGuid>dfa1ec6f-4abe-4b38-b1b1-142d41af93b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Status ' or . = 'Status ')]</value>
      <webElementGuid>aa087336-16fe-4175-ac7d-358ad7eebf6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
