<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_ttddisini</name>
   <tag></tag>
   <elementGuidId>c9a7e0ea-496d-4e32-af8b-0d26f9896855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Meterai'])[1]/following::div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ac8a8204-152a-4339-9c99-314fe72fdcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-content</value>
      <webElementGuid>213e1e57-6416-4148-9bbc-cab2ca68d635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CustomerTTD disini</value>
      <webElementGuid>1245015d-9886-4474-bcbe-f76a42428b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-hide navbar-static pace-done menu-expanded&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;main-panel&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;content-wrapper&quot;]/app-setting-signer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 align-items-center justify-content-center&quot;]/app-document-anotate[1]/section[@class=&quot;document-annotation&quot;]/section[@class=&quot;box&quot;]/div[@class=&quot;box-container ng-star-inserted&quot;]/app-bbox[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;cdk-drag bbox-draggable ttd&quot;]/div[@class=&quot;box-content&quot;]</value>
      <webElementGuid>fb798070-8b32-4ae7-b097-c3f659eb498f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meterai'])[1]/following::div[3]</value>
      <webElementGuid>211ccbfa-5f45-4fd4-b922-f258ecde1a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paraf'])[1]/following::div[3]</value>
      <webElementGuid>19e516cb-51a4-4e86-b12a-a25eb417d56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-bbox/div/div</value>
      <webElementGuid>c9249ae8-e4d0-452e-9715-ea5bf8496497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CustomerTTD disini' or . = 'CustomerTTD disini')]</value>
      <webElementGuid>bc62c38e-e824-4811-86b4-d8d43382453f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
