<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Psre</name>
   <tag></tag>
   <elementGuidId>c69a6068-b0b1-4c44-a1bc-bdef185fd6f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;vendorCode&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vendorCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>225e675f-94a5-46ea-8a8b-2cd84b235608</webElementGuid>
   </webElementProperties>
</WebElementEntity>
