<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Per Document</name>
   <tag></tag>
   <elementGuidId>1fed4f47-b299-4c3d-ba1a-87a3bd924fb6</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aa88e97a7ffb-0']/span</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ng-option-label.ng-star-inserted</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[@class = 'ng-option-label ng-star-inserted' and @ng-reflect-ng-item-label = 'Per Document' and (text() = 'Per Document' or . = 'Per Document')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff27bf04-c0c1-4c90-93dd-c55cb8fe8127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-option-label ng-star-inserted</value>
      <webElementGuid>ae3c2bb9-4643-4d51-88e8-10bd6952790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-item-label</name>
      <type>Main</type>
      <value>Per Document</value>
      <webElementGuid>834cfb72-eba7-42c5-8236-24645b39c7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-escape</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb1a2234-a1be-4f2b-91a4-3234219850a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Per Document</value>
      <webElementGuid>e74c5338-1228-4776-aa8b-a43a8f10e24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aa88e97a7ffb-0&quot;)/span[@class=&quot;ng-option-label ng-star-inserted&quot;]</value>
      <webElementGuid>f7cd89a6-dd17-47b7-9774-3a1a01635735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aa88e97a7ffb-0']/span</value>
      <webElementGuid>c34a28ef-1221-494b-82a8-20a3d307d3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select payment sign type'])[1]/following::span[7]</value>
      <webElementGuid>cf1ac5b6-6a9d-482b-8180-727cb1ef1e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::span[7]</value>
      <webElementGuid>de8f24b9-f1ae-413c-a167-bf9c5e93c604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Per Sign'])[1]/preceding::span[1]</value>
      <webElementGuid>fb67c988-6d9c-4211-a7d0-3d96d23dc56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Per Document']/parent::*</value>
      <webElementGuid>009c0b05-a2bc-453d-abf7-e1d24108985e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span</value>
      <webElementGuid>d4510473-efec-4912-97c8-eb31118816f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Per Document' or . = 'Per Document')]</value>
      <webElementGuid>4598a282-15de-43e5-98a6-df130a0845b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
