<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_DocTempDescription</name>
   <tag></tag>
   <elementGuidId>770701fd-b5ae-4d66-9928-18b92a152a38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentTemplateDescription&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentTemplateDescription&quot;]</value>
      <webElementGuid>0f6facd1-e2b6-434c-b859-029ac3f6914d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
