<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_DocTempName</name>
   <tag></tag>
   <elementGuidId>cef9ad5d-b69f-4370-bc1a-266a1e0c91e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentTemplateName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentTemplateName&quot;]</value>
      <webElementGuid>5169b9ce-3da0-440b-96b2-3378532e6614</webElementGuid>
   </webElementProperties>
</WebElementEntity>
