<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>view_DocTempCode</name>
   <tag></tag>
   <elementGuidId>dc42133c-947c-47d3-a22c-36d9ffcea868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentTemplateCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentTemplateCode&quot;]</value>
      <webElementGuid>b2a78c8a-1cfc-44ea-ad27-7eb49cac577b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
