<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputTenant</name>
   <tag></tag>
   <elementGuidId>0555667c-2df0-4cd8-8095-e26a67923768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tenantCode&quot;]/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tenantCode&quot;]/div/div/div[2]/input</value>
      <webElementGuid>86775e1f-da7a-4c41-ad0a-3f17d5296ae9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
