<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputTipeSaldo</name>
   <tag></tag>
   <elementGuidId>9cacdbf2-e67e-4923-b826-91d5e22efd63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;balanceType&quot;]/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;balanceType&quot;]/div/div/div[2]/input</value>
      <webElementGuid>35a6f98b-4938-405a-9694-e578d137871b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
