<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_bahasa</name>
   <tag></tag>
   <elementGuidId>c83ffbca-4241-41eb-b3e4-5b2c1becf090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dropdown-flag&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dropdown-flag&quot;]</value>
      <webElementGuid>cb7608a5-4674-4bdb-a182-a0e3e0bc6262</webElementGuid>
   </webElementProperties>
</WebElementEntity>
