<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog</name>
   <tag></tag>
   <elementGuidId>16a3e722-b7cc-47db-aba8-0f7eda46a547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'alertdialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div/div[2]</value>
      <webElementGuid>cdfb24f6-c47c-4769-a4b3-c898ca514815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alertdialog</value>
      <webElementGuid>0caf6292-66c4-450a-9d57-19e9c2bf6a3c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
