<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_bahasa</name>
   <tag></tag>
   <elementGuidId>445e5730-7ed8-4a7e-9ed0-3e244bd972dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dropdown-flag&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dropdown-flag&quot;]</value>
      <webElementGuid>868c37ea-9aba-488f-9fcf-d1d7c633a11b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
