<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YaKirimOTP</name>
   <tag></tag>
   <elementGuidId>bf95fb1a-c5fe-4816-9b6f-2bc7b302ef64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Ya' or . = 'Ya')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-confirmation-modal/div[2]/button[2]</value>
      <webElementGuid>11c639de-ae1c-4204-be6e-397b3fd227a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>508eccd1-9b37-428d-a4c2-373f259afeb5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
