<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessagePopUp</name>
   <tag></tag>
   <elementGuidId>86bb97a7-dded-4e96-9856-a1ce73e5d4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;swal2-content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;swal2-content&quot;]</value>
      <webElementGuid>37bc1240-1508-4bb1-abd0-ffc21eb7fe05</webElementGuid>
   </webElementProperties>
</WebElementEntity>
