<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RatingBintang</name>
   <tag></tag>
   <elementGuidId>7a231a9d-5146-44cf-87ca-e76b580b6277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;rating&quot;]/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;rating&quot;]/span[2]/span</value>
      <webElementGuid>3233547b-3c90-42fe-830b-d0dcad842866</webElementGuid>
   </webElementProperties>
</WebElementEntity>
