<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_modifyDownload</name>
   <tag></tag>
   <elementGuidId>5e33b4a7-9e7a-4acb-8bf4-7abe253c2c28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>f0838f82-5659-4c3c-b665-d11b7a122f10</webElementGuid>
   </webElementProperties>
</WebElementEntity>
