<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SetUlang</name>
   <tag></tag>
   <elementGuidId>bb60c026-5dec-4c02-a130-78139c61f697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchForm&quot;]/div[2]/div/button[1]</value>
      <webElementGuid>5858a166-7658-4320-85f0-ef48166d19ea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
