<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaPelanggan</name>
   <tag></tag>
   <elementGuidId>2caa23b0-fcf8-4891-bbb1-f8545a459f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;customerName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;customerName&quot;]</value>
      <webElementGuid>1664c10b-261b-4acd-8c51-c1f97ec259bc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
