<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoKontrak</name>
   <tag></tag>
   <elementGuidId>ee0b3209-a76a-4021-a425-07c172860eab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;refNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;refNumber&quot;]</value>
      <webElementGuid>67293580-8709-4b7f-b977-a897ae1b5d05</webElementGuid>
   </webElementProperties>
</WebElementEntity>
