<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputVendor</name>
   <tag></tag>
   <elementGuidId>2987f081-56c7-4c13-bac5-a4afee25150d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;vendorCode&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;vendorCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>054907f9-9064-40d2-ab16-f270d79154cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
