<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Beranda</name>
   <tag></tag>
   <elementGuidId>ad10b7b7-f816-405a-827f-ecbc62bb54ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::a[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ng-tns-c100-1.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f0f042a-87ce-4b57-a810-51480a6c6183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c100-1 ng-star-inserted</value>
      <webElementGuid>a47cb36e-e23e-49c3-94c2-7030574feb7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard</value>
      <webElementGuid>d499bb78-5a21-411d-9f5f-a5ced0523159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beranda</value>
      <webElementGuid>49844aef-38c8-4308-963e-c27a5bb425ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout navbar-static pace-done menu-expanded menu-open vertical-menu&quot;]/app-root[1]/app-full-layout[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;app-sidebar main-menu menu-fixed menu-native-scroll expanded ng-star-inserted&quot;]/app-sidebar[@class=&quot;ng-tns-c100-1&quot;]/div[@class=&quot;sidebar-content main-menu-content ng-tns-c100-1 ps&quot;]/div[@class=&quot;nav-container ng-tns-c100-1&quot;]/ul[@class=&quot;navigation ng-tns-c100-1&quot;]/li[@class=&quot;ng-tns-c100-1 ng-star-inserted active&quot;]/a[@class=&quot;ng-tns-c100-1 ng-star-inserted&quot;]</value>
      <webElementGuid>60596eb8-ac4f-40c8-81fe-fafd67c41daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::a[4]</value>
      <webElementGuid>239f1adf-59fd-4e9a-a157-f7b0a9d9ce85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Kode Akses'])[1]/following::a[5]</value>
      <webElementGuid>2cf73da6-c20b-4368-8a4d-abbf1015bd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pencarian Dokumen'])[1]/preceding::a[1]</value>
      <webElementGuid>cffc8c1e-a7d2-44c3-83f2-b2065f15f6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/dashboard')])[2]</value>
      <webElementGuid>c3b704e2-29c9-4fa7-b34e-bb61d3b307c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-sidebar/div[2]/div/ul/li/a</value>
      <webElementGuid>ed500fe0-3b68-4a3d-866d-905d4ec78126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard' and (text() = 'Beranda' or . = 'Beranda')]</value>
      <webElementGuid>852f71ff-e144-4a2b-a412-6d078e116520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
