<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_MenyetujuiMenandatangani</name>
   <tag></tag>
   <elementGuidId>743654bb-8ef6-49e4-b1de-5fdf65e8b345</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='OTP'])[1]/following::span[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-small-2.mb-3.font-weight-normal</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'font-small-2 mb-3 font-weight-normal' and (text() = ' Saya menyetujui menandatangani dokumen ini' or . = ' Saya menyetujui menandatangani dokumen ini')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b8dbd0d9-3673-4071-ba18-7414a2776bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-small-2 mb-3 font-weight-normal</value>
      <webElementGuid>1d6d86c0-8600-4386-a1c4-ea9cf53c9073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Saya menyetujui menandatangani dokumen ini</value>
      <webElementGuid>4651f4a5-53a5-43b6-b249-7376557ddbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-expanded menu-open vertical-menu navbar-static pace-done modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-l&quot;]/div[@class=&quot;modal-content&quot;]/app-signer-signing-verification[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row-1&quot;]/div[@class=&quot;checkbox auth-checkbox&quot;]/label[1]/span[@class=&quot;font-small-2 mb-3 font-weight-normal&quot;]</value>
      <webElementGuid>f0e93e84-28d4-4054-ae39-b265e90fcd40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rememberMe</value>
      <webElementGuid>ea81b1aa-4660-4e1f-930a-b0648ba7d489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>393f3a98-1f13-411c-849b-5a716c92e640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OTP'])[1]/following::span[1]</value>
      <webElementGuid>3053efec-3d8b-4591-abfa-54ab03929ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Biometric'])[1]/following::span[2]</value>
      <webElementGuid>b142274a-8cc4-4383-9e0f-8708de7a335b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjut'])[1]/preceding::span[1]</value>
      <webElementGuid>fccae2cd-3ca4-44c7-badd-e0103cb9efb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label/span</value>
      <webElementGuid>3f63203f-4724-4212-87f9-6fddbc659af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Saya menyetujui menandatangani dokumen ini' or . = ' Saya menyetujui menandatangani dokumen ini')]</value>
      <webElementGuid>f2dcaf71-8c8d-45a2-88a8-c128531c4a86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
