<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog_OK</name>
   <tag></tag>
   <elementGuidId>d720cedf-9f29-4c1e-953a-3c25d25f0632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div/div[3]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[3]/button[1]</value>
      <webElementGuid>50a21b73-0cc0-4ef5-9c03-d50684ef0fa6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
