<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP</name>
   <tag></tag>
   <elementGuidId>73542e59-65fe-4842-9a91-ef09c46e44cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='otp']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;otp&quot;)</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5a03c2d-0692-40f9-b356-8438b4d2b843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>58ece7ef-a15a-401a-ba24-0b55467cd25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>366d25d4-9ee8-4d3a-b0fb-f7edd326d013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otp</value>
      <webElementGuid>d7932737-639c-4a92-88ec-6a2e6974988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Insert OTP Code</value>
      <webElementGuid>182bf752-008c-4606-975a-f2cee17700d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>85054c7a-2660-476e-9fb3-544eb7607754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2 ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1dabc0de-49c7-4f08-a6ad-f94f80995b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otp&quot;)</value>
      <webElementGuid>95f8ec54-1b05-44b2-b0e8-45577e7b99c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='otp']</value>
      <webElementGuid>814fb07d-655e-4b7b-9925-55d8c541bbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6b581bab-4bb4-4f82-ba78-3c65e2cf957d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'otp' and @placeholder = 'Insert OTP Code']</value>
      <webElementGuid>92b907fa-76d2-4577-ac50-8693cb108ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
