<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phoneNoAfterKonfirmasi</name>
   <tag></tag>
   <elementGuidId>33ffcebe-06e8-495e-84ee-50f3421b48f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51086e17-b4ea-4b0a-ab38-53e0d56b665a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>phoneNo</value>
      <webElementGuid>9dc48962-9eb2-4ff8-b626-4ca3a1ff4993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>PhoneNo</value>
      <webElementGuid>66294d5c-b804-4a5d-9b23-9b0acce434ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNo</value>
      <webElementGuid>25b3939e-e8a1-4cbc-b222-190eba2e6438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Handphone</value>
      <webElementGuid>5a29f8b8-07f3-4b0d-b095-524f3e2386f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-2 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>86624fb8-d4a1-4036-8fa2-9d5e4d1ca7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNo&quot;)</value>
      <webElementGuid>4d8d6c52-6e62-4ab6-b8df-e7d18bf3e86d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNo']</value>
      <webElementGuid>befd6b47-2038-4ebe-810a-f43ec5bdc2d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>59191abf-c364-4d0e-9266-0d666215f0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'phoneNo' and @id = 'phoneNo' and @placeholder = 'No Handphone']</value>
      <webElementGuid>05fa9d0c-bc8c-4cf7-b5c7-b2b1576bb5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
