<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_success</name>
   <tag></tag>
   <elementGuidId>9741a37d-017f-4a7c-8136-31b236ccc342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-progress-signing/div/div/div/div/div[1]/div[1]/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-progress-signing/div/div/div/div/div[1]/div[1]/div[2]/p</value>
      <webElementGuid>e653eeeb-5b29-43f0-b027-b024cc0b2936</webElementGuid>
   </webElementProperties>
</WebElementEntity>
