<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_RequestOTP</name>
   <tag></tag>
   <elementGuidId>37607f95-23e6-424e-ba0d-7bdfa36f1881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-signer-signing-otp-verification/form/div/div[1]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.font-large-1.text-center.text-bold-700.px-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>732cd5f7-19b9-4dad-a8f9-0faca9ca8195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-signer-signing-otp-verification/form/div/div[1]/div/p</value>
      <webElementGuid>d4a20171-e6a5-44bc-bcd5-b322007eb413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Request OTP</value>
      <webElementGuid>2e728b20-9ab5-4a62-96fc-7a4eb195016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-signer-signing-otp-verification/form/div/div[1]/div/p</value>
      <webElementGuid>e710276b-56e8-43fa-877a-d6860a489d72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::p[1]</value>
      <webElementGuid>163947a2-406b-4f67-b460-490d0e9c63f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::p[1]</value>
      <webElementGuid>036c29cf-3459-4d9f-997c-1d19b0b587b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No HP'])[1]/preceding::p[1]</value>
      <webElementGuid>75035bbb-398b-4e71-b04a-e5f3a6dee35e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berhasil kirim OTP'])[1]/preceding::p[1]</value>
      <webElementGuid>b5fe8b5c-4275-4c03-a874-36177ab07122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Request OTP']/parent::*</value>
      <webElementGuid>2d63cc49-b465-420a-babe-3393dca43f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>e80d1f17-1211-4be2-a799-ce9aea2f61b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Request OTP' or . = 'Request OTP')]</value>
      <webElementGuid>219c8add-5d5e-49f2-abc8-85e1b5449a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
