<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_phoneNo</name>
   <tag></tag>
   <elementGuidId>0d397624-7ad1-43ff-8efe-8903ed3b5031</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;phone&quot;]</value>
      <webElementGuid>bb42a223-27dc-4397-9e9a-d86c5da709a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
