<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_starMasukan</name>
   <tag></tag>
   <elementGuidId>458dbd76-bcef-46b4-8eb0-d5cc76da31f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ngb-rating[@id='rating']/span[10]/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//ngb-rating[@id='rating']/span[10]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4495bebf-6e22-4095-be03-3bb86cf4daad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-star-on px-2 ng-star-inserted filled</value>
      <webElementGuid>b82b7621-ea56-4a39-97be-4ca9f3dd4094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ngb-rating[@id='rating']/span[10]/span</value>
      <webElementGuid>5a58ed5c-6f8b-4dcd-be05-2932dbd32c2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngb-rating[@id='rating']/span[10]/span</value>
      <webElementGuid>8ebf638b-4685-4f9b-972b-170277ea652f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]/span</value>
      <webElementGuid>62b3e082-0aab-45f5-8d0a-8c0b481136a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
