<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Catatan</name>
   <tag></tag>
   <elementGuidId>f8eb9745-5b08-4066-8b59-969cfc51a6c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;notes&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;notes&quot;]</value>
      <webElementGuid>6cae7967-4de1-4221-b853-8af5e53918a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
