<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Batal</name>
   <tag></tag>
   <elementGuidId>56c04aaf-cbcf-4ba1-906a-7761d6751e26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-service-balance/div[2]/div/div/div/div/div/div/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-service-balance/div[2]/div/div/div/div/div/div/button[1]</value>
      <webElementGuid>11b4bcba-d40d-4db7-98f2-ceb8e148e867</webElementGuid>
   </webElementProperties>
</WebElementEntity>
