<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyObject</name>
   <tag></tag>
   <elementGuidId>9bae2bf7-fb18-4426-8bb2-3119593e9d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;OTP@DJP&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;OTP@DJP&quot;]</value>
      <webElementGuid>199a322c-8d9b-4b38-9857-e58299711860</webElementGuid>
   </webElementProperties>
</WebElementEntity>
