<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PilihFileKTP</name>
   <tag></tag>
   <elementGuidId>e75603a3-9233-4377-859d-c0ac56c39d5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[16]/div[2]/div[1]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[16]/div[2]/div[1]/label</value>
      <webElementGuid>082fca23-c7c6-4bc2-8b7b-cf9e9f9b9281</webElementGuid>
   </webElementProperties>
</WebElementEntity>
