<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Setuju</name>
   <tag></tag>
   <elementGuidId>8feba22f-bb8d-4dec-9fbe-88250df9053a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[18]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[18]/div/div/label/span</value>
      <webElementGuid>4c3b2186-bc90-4406-b1d6-4d8f175f3dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>20d6b8d1-b6d7-4ad7-84ae-a9baf81a1eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya Menerima</value>
      <webElementGuid>3e2b916a-a53f-4bda-92c9-a5abc69b10ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
