<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Setuju</name>
   <tag></tag>
   <elementGuidId>8feba22f-bb8d-4dec-9fbe-88250df9053a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[18]/div/div/label/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[18]/div/div/label/span</value>
      <webElementGuid>b7b9857c-1cbc-4d0b-b3fa-bef15f7f8976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>b4ea6c71-af77-4e97-9924-3087bca7c5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya Menerima</value>
      <webElementGuid>ea12d5ff-70be-43a6-9449-0d16f6b232cf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
