<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SyaratdanKetentuan</name>
   <tag></tag>
   <elementGuidId>2f2df1f0-a7e7-4a92-8d3b-634806cd173e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[17]/div/label/span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[17]/div/label/span</value>
      <webElementGuid>423c95a1-2823-4967-9cea-a69aa39b6c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>5a4f380b-0274-400b-901b-9998fda55a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya Menerima</value>
      <webElementGuid>1ec59b0b-b6e0-45fe-b2ba-2f8d896d7ff2</webElementGuid>
   </webElementProperties>
</WebElementEntity>
