<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SyaratdanKetentuan</name>
   <tag></tag>
   <elementGuidId>2f2df1f0-a7e7-4a92-8d3b-634806cd173e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[17]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//section[@id='regestration']/div/div/div/div/div/div/div/form/div[17]/div/label/span</value>
      <webElementGuid>adf47e58-e67b-49e0-b476-2bbee25644af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>cb826a05-039f-4ec9-9698-485f8b1d8709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Saya Menerima</value>
      <webElementGuid>22402515-5be8-496e-a885-3ffcdeab3ac4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
