<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_SyaratdanKetentuan</name>
   <tag></tag>
   <elementGuidId>2f2df1f0-a7e7-4a92-8d3b-634806cd173e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@formcontrolname = 'acceptTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;auth-login&quot;]</value>
      <webElementGuid>2c3223e7-5c01-4d52-b520-15877dacfc81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>acceptTerms</value>
      <webElementGuid>e8dc6f40-244a-47d0-a0e9-61012e974266</webElementGuid>
   </webElementProperties>
</WebElementEntity>
