<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog</name>
   <tag></tag>
   <elementGuidId>387091b5-022b-4d9d-a418-b12c62b58d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'alertdialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div/div[2]</value>
      <webElementGuid>b72bb49b-15d5-4cc8-8688-5d401caa19a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alertdialog</value>
      <webElementGuid>ce636709-2973-4437-a8b0-8b3bf9b8039c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
