<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaLengkap</name>
   <tag></tag>
   <elementGuidId>63d6b2da-0d96-4e64-8d2e-a32a9b72daa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;name&quot;]</value>
      <webElementGuid>255eefde-b3c8-44da-ac1b-9760db6fa23a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
