<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP</name>
   <tag></tag>
   <elementGuidId>2c57565c-e843-4bec-961b-d5d0e96cba75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;otp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;otp&quot;]</value>
      <webElementGuid>5f51cb94-d4ff-4f0d-a5c9-4ff3026d9145</webElementGuid>
   </webElementProperties>
</WebElementEntity>
