<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KodePos</name>
   <tag></tag>
   <elementGuidId>f708332f-4c66-48c1-864a-25363c639358</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;zip&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;zip&quot;]</value>
      <webElementGuid>6677d3de-7cd6-4baf-a29e-879fba6bb3df</webElementGuid>
   </webElementProperties>
</WebElementEntity>
