<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AlamatLengkap</name>
   <tag></tag>
   <elementGuidId>8a251503-8209-42eb-8a2e-9ea9070529a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;address&quot;]</value>
      <webElementGuid>57dd7bd0-08bb-4218-a45f-a3f7f322d628</webElementGuid>
   </webElementProperties>
</WebElementEntity>
