<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kecamatan_TknAja</name>
   <tag></tag>
   <elementGuidId>92c91a58-cf28-49e2-b775-2e6fdf1a21e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[12]/ng-select/div/div/div[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;regestration&quot;]/div/div/div/div/div/div/div/form/div[12]/ng-select/div/div/div[2]/span[2]</value>
      <webElementGuid>d277fb50-a3e7-49c0-b206-82f1f7b209ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
