<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Pria</name>
   <tag></tag>
   <elementGuidId>682b762f-b61e-47b1-b575-bb5e331f081e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;male&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;male&quot;]</value>
      <webElementGuid>12bd805a-28c6-41d5-a67c-137b3a7c59d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
