<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_PSrE</name>
   <tag></tag>
   <elementGuidId>04fbea65-e043-488d-be35-1af7b1f128b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;psre&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;psre&quot;]/div/div/div[3]/input</value>
      <webElementGuid>4eb0ebbd-e794-4c85-b2d2-dc7a99734cfb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
