<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_Wilayah</name>
   <tag></tag>
   <elementGuidId>0afc6b86-c5a4-45a5-b72e-301f90aecbc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#regionCode > div.ng-select-container.ng-has-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ng-select[@id='regionCode']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dc3656b7-eef1-47a6-a742-73333ed8725a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-select-container ng-has-value</value>
      <webElementGuid>86ea14c8-8d66-4f9c-970a-73ec2de313a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select region×All×</value>
      <webElementGuid>50ada8e5-a024-4412-92aa-2094152dd9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;regionCode&quot;)/div[@class=&quot;ng-select-container ng-has-value&quot;]</value>
      <webElementGuid>f82cf762-d531-4910-b822-403fc33eab61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='regionCode']/div</value>
      <webElementGuid>6ff9acc9-de8d-44f1-b9ad-62487450a4fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wilayah'])[1]/following::div[2]</value>
      <webElementGuid>e33fd83a-0a88-4ab6-b3c9-b042954f8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::div[6]</value>
      <webElementGuid>11de5089-26ea-4e74-87f6-175549087ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/app-question/app-select/div/div[2]/ng-select/div</value>
      <webElementGuid>5cf14f78-edae-4a26-8639-606aa8e2c078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select region×All×' or . = 'Select region×All×')]</value>
      <webElementGuid>de3f05b4-db3c-4cb4-bb9f-682345554e04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
