<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalSelesaiSampai</name>
   <tag></tag>
   <elementGuidId>4496ae44-064e-4a9b-a841-f25b907018f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#completedDateEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='completedDateEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8c491a4-8e3e-4bcd-aeb7-5d67746cab29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>301a5d70-600c-4ce4-8ea7-9d5114d97455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b97eeeab-05ba-4e9c-96cc-c70e9010ff44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>completedDateEnd</value>
      <webElementGuid>2627f9e1-a46d-4c6a-b45e-08de42a92e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>completedDateEnd</value>
      <webElementGuid>aab02076-54e0-41c6-98b8-083dd87bd398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>bed476db-f5fe-4ea9-afba-8c64f30699d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;completedDateEnd&quot;)</value>
      <webElementGuid>d0f328a9-dba2-4c4c-b390-40a185cca748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='completedDateEnd']</value>
      <webElementGuid>c07a7f92-6498-4866-b370-ab6036e0dfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>17870432-cc64-4180-9387-37adfb18c899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>b9e763ef-2875-4f9a-b027-e7fb72dbbe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'completedDateEnd' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>05550d98-c007-45ce-90c4-bc8984192fd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
