<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NomorKontrak</name>
   <tag></tag>
   <elementGuidId>be34d9de-3863-4e2d-8ee6-981776732f95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#refNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='refNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cd376b5-9686-42c7-886a-0cf1a2ea3c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5387360b-8271-477c-bda6-f5ee16180811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>16949e4b-70d7-4b49-a0b2-75d4f2994d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>refNumber</value>
      <webElementGuid>85f1a946-bd2d-4b10-8071-3a8866242eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>refNumber</value>
      <webElementGuid>306688a6-2a54-4a8a-88e7-0d9c444af0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type ref number here</value>
      <webElementGuid>cb0c7753-8cff-4e04-b0ca-e46367c0399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3338970-6a2e-413e-a00d-8e9476766db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refNumber&quot;)</value>
      <webElementGuid>f74ea000-30e6-498d-b3f7-6e06a52e2788</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='refNumber']</value>
      <webElementGuid>ff2b601d-1fcb-4cbe-99c1-8e426b2651ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>2fcd5850-c36e-4ac0-aa8f-76b4b6d9a0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>8f7c55f4-ae19-4d95-9bce-6a3ae34f37b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'refNumber' and @placeholder = 'Type ref number here']</value>
      <webElementGuid>73584b4b-2e9e-41ce-8ed6-76d089f615b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
