<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPermintaanDari</name>
   <tag></tag>
   <elementGuidId>68b31ea1-43a0-4e9e-bce8-e5c099da108e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requestedDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requestedDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8d185ca4-7141-4001-9d90-c3079b0a0366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a3b8adb-d38a-4754-b586-d53f9800251a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>7c06fea8-2069-4953-927c-cf71e42a887f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>requestedDateStart</value>
      <webElementGuid>74193dc5-7170-4da9-888e-b95f21da59ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requestedDateStart</value>
      <webElementGuid>430e70ca-50e8-4896-a3bd-d9d24e5dd667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>ae042889-4dac-42b7-bc80-b6ce3e92e75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestedDateStart&quot;)</value>
      <webElementGuid>e45cf58b-455e-44e4-a573-c0c93e122328</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requestedDateStart']</value>
      <webElementGuid>934d3577-88a1-4257-a6cf-ba632e002487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[3]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>c125a9bb-a402-41c4-b754-00bc62aca415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/div/div[2]/div/input</value>
      <webElementGuid>994ab0bb-137f-403a-9b07-c19ff741c92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'requestedDateStart' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>1d0616c8-95eb-408b-be52-f4c98fa5fee8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
