<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalPermintaanSampai</name>
   <tag></tag>
   <elementGuidId>3246bb22-a5fd-4471-934f-c575da27660d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#requestedDateEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='requestedDateEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55729393-118c-446c-b80c-d09e75edb858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec35d01b-5f9e-493e-889d-81fb834eabee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>168eafe0-319b-48a6-bc60-d49822e1b69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>requestedDateEnd</value>
      <webElementGuid>3f3b3996-f0c2-4d8c-b6f2-7135f1e12548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>requestedDateEnd</value>
      <webElementGuid>6c3be983-de49-42b3-b273-9f9fd28c8752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>016dbd11-7a18-410d-b6d0-4d0734d2fea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;requestedDateEnd&quot;)</value>
      <webElementGuid>81a71bae-2055-439f-af1f-814edfe6255f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='requestedDateEnd']</value>
      <webElementGuid>a9fede07-d2a2-4175-91c5-ab8e8e5f34ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[4]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>f67decfb-70ee-4624-b779-3752436b7da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>2cf3ecb2-c763-45e9-8720-61d849a19f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'requestedDateEnd' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>ac68b478-6118-4468-82d5-d362226817d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
