<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NamaPelanggan</name>
   <tag></tag>
   <elementGuidId>3fdf7ca3-3dcc-4106-8baa-f182ccbdf8ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customerName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customerName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6fee0a35-f70c-4f69-8764-8ea5bfb73b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9638b941-a9ab-4030-a0d9-e04349da2a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>6b36b7c9-e612-4510-a6a3-4ffb7c75b7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>customerName</value>
      <webElementGuid>662d1ecf-6920-4681-a596-db7ffa503762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customerName</value>
      <webElementGuid>57789563-9ab3-4771-bf3c-94aef783d98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type customer here</value>
      <webElementGuid>ac692e64-1ba9-488c-a6d7-04468087429c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9c0f6018-16bd-4982-88c2-5547fd0bf96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customerName&quot;)</value>
      <webElementGuid>22232a03-eb33-44fa-a39c-8a2e5cc40a7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customerName']</value>
      <webElementGuid>8efc8f52-4b66-4da7-afec-38041b34cf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>5ea182df-1990-4e19-870a-a30f7e6ac36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>2e982f2f-7d4c-43a7-91e4-3398ec1023e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customerName' and @placeholder = 'Type customer here']</value>
      <webElementGuid>ed17db97-3dbf-4241-94f3-e1581802c889</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
