<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalSelesaiDari</name>
   <tag></tag>
   <elementGuidId>1f4c7480-a513-4456-a663-902802350835</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#completedDateStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='completedDateStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>432cdb00-68cf-4e55-b329-e19e8b98caa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97985fef-c905-4c49-8ab7-c36bd4917149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a0299464-10be-497c-9765-adf7a41772e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>completedDateStart</value>
      <webElementGuid>87600539-c216-41b7-8cfa-8ead1b3a6e7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>completedDateStart</value>
      <webElementGuid>b58e67e1-7ec3-4d11-a125-64b8bcdd11c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>f54c6161-ed92-4ba7-a842-f4da3ef2ff05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;completedDateStart&quot;)</value>
      <webElementGuid>b3513fd9-c3bb-44d6-aa9c-c101a6376ac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='completedDateStart']</value>
      <webElementGuid>6c82b8cc-b1db-4c8c-93ab-333cac9028aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchForm']/div/div[5]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>fa313133-3dd3-4521-b581-4046001a7e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/app-question/app-date/div/div[2]/div/input</value>
      <webElementGuid>b77fb067-d17e-4044-acc6-055af24beb3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'completedDateStart' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>c42a7676-278b-4072-af66-6f5269e675e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
