<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Register</name>
   <tag></tag>
   <elementGuidId>bfd654fc-5a9a-4e08-b532-2c35aa9a77ef</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;audit\&quot;: {\r\n        \&quot;callerId\&quot;: \&quot;USER@AD-INS.COM\&quot;\r\n    },\r\n    \&quot;nama\&quot;: \&quot;Test nama\&quot;,\r\n    \&quot;email\&quot;: \&quot;test123@gmail.com\&quot;,\r\n    \&quot;tmpLahir\&quot;: \&quot;tempat lahir\&quot;,\r\n    \&quot;tglLahir\&quot;: \&quot;2023-03-28\&quot;,\r\n    \&quot;jenisKelamin\&quot;: \&quot;M\&quot;,\r\n    \&quot;tlp\&quot;: \&quot;0812345678\&quot;,\r\n    \&quot;idKtp\&quot;: \&quot;1234567890123456\&quot;,\r\n    \&quot;alamat\&quot;: \&quot;alamat\&quot;,\r\n    \&quot;kecamatan\&quot;: \&quot;kecamatan\&quot;,\r\n    \&quot;kelurahan\&quot;: \&quot;kelurahan\&quot;,\r\n    \&quot;kota\&quot;: \&quot;kota\&quot;,\r\n    \&quot;provinsi\&quot;: \&quot;provinsi\&quot;,\r\n    \&quot;kodePos\&quot;: \&quot;123456\&quot;,\r\n    \&quot;selfPhoto\&quot;: \&quot;selfPhoto\&quot;,\r\n    \&quot;idPhoto\&quot;: \&quot;idPhoto\&quot;,\r\n    \&quot;password\&quot;: \&quot;Password123!\&quot;\r\n}\r\n&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>1c4926d0-8447-40d1-92bc-507c53f76002</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>06968266-469c-4ca8-8e18-9f62db0e7498</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-api-key</name>
      <type>Main</type>
      <value>${api_key}@${tenant_code}</value>
      <webElementGuid>8f0317fc-1f29-4909-a70e-1bb3e033f247</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${base_url}/user/register</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.base_url</defaultValue>
      <description></description>
      <id>45248845-b2a3-42ff-a1a5-f1c525d2f959</id>
      <masked>false</masked>
      <name>base_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.api_key</defaultValue>
      <description></description>
      <id>06bec374-a825-4f7c-a2d7-16124b8d7847</id>
      <masked>false</masked>
      <name>api_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.tenant_code</defaultValue>
      <description></description>
      <id>dfe4c694-3be4-44ab-92f8-d8d9e5da661a</id>
      <masked>false</masked>
      <name>tenant_code</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
