<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>Sign Document</name>
   <tag></tag>
   <elementGuidId>448f5b77-7953-424a-95be-5d6677fb14d5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\r\n    \&quot;audit\&quot;: {\r\n        \&quot;callerId\&quot;: \&quot;USER@AD-INS.COM\&quot;\r\n    },\r\n    \&quot;documentId\&quot;: [\r\n        \&quot;00155D0A-AD03-8C34-11EC-DAB74EE7FEE0\&quot;,\r\n        \&quot;00155D0A-AD03-8C34-11EC-DAB74EE7FEE1\&quot;,\r\n        \&quot;00155D0A-AD03-8C34-11EC-DAB74EE7FEE2\&quot;\r\n    ],\r\n    \&quot;email\&quot;: \&quot;test@gmail.com\&quot;,\r\n    \&quot;password\&quot;: \&quot;Password123!\&quot;,\r\n    \&quot;ipAddress\&quot;: \&quot;192.158.1.38\&quot;,\r\n    \&quot;browserInfo\&quot;: \&quot;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36\&quot;,\r\n    \&quot;otp\&quot;: \&quot;912834\&quot;,\r\n    \&quot;selfPhoto\&quot;: \&quot;\&quot;\r\n}&quot;,
  &quot;contentType&quot;: &quot;application/json&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Content-Type</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>582561fc-fe72-44fe-a89f-c817bba2e359</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>Accept</name>
      <type>Main</type>
      <value>application/json</value>
      <webElementGuid>d78c63a3-f2c4-45cd-82f4-6c492599a587</webElementGuid>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-api-key</name>
      <type>Main</type>
      <value>${api_key}@${tenant_code}</value>
      <webElementGuid>7e02d7bb-ca44-4787-9186-8ef88b503b00</webElementGuid>
   </httpHeaderProperties>
   <katalonVersion>8.5.5</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${base_url}/document/signDocument</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.base_url</defaultValue>
      <description></description>
      <id>e629eaaa-d115-4310-b2f6-4616c91a1517</id>
      <masked>false</masked>
      <name>base_url</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.api_key</defaultValue>
      <description></description>
      <id>b6dc925f-9a02-45f1-aace-41226062c82f</id>
      <masked>false</masked>
      <name>api_key</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.tenant_code</defaultValue>
      <description></description>
      <id>95a66518-9f1f-420d-8d2f-852edf359004</id>
      <masked>false</masked>
      <name>tenant_code</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
