<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_certificateStatus</name>
   <tag></tag>
   <elementGuidId>8cb03d92-78d3-4779-82ec-c8a5d691cfe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;certificateStatus&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;certificateStatus&quot;]</value>
      <webElementGuid>23a981fe-179d-4052-b505-a1540567f689</webElementGuid>
   </webElementProperties>
</WebElementEntity>
