<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama</name>
   <tag></tag>
   <elementGuidId>eb2f560b-24ba-4906-a94a-0c5a8c271693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nama&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nama&quot;]</value>
      <webElementGuid>2a10d6d2-5355-4a4c-ad57-35d6bc0be501</webElementGuid>
   </webElementProperties>
</WebElementEntity>
