<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK</name>
   <tag></tag>
   <elementGuidId>a246567d-b6a8-4840-8626-47acd1c9c83d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nik&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nik&quot;]</value>
      <webElementGuid>0e20ab42-0d6c-40d7-9ab9-5bdad1dba140</webElementGuid>
   </webElementProperties>
</WebElementEntity>
