<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ExpiredDate</name>
   <tag></tag>
   <elementGuidId>b1f997d5-02ef-46fb-9ba7-2aceb3cd967b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;certExp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;certExp&quot;]</value>
      <webElementGuid>62b022f5-7f0b-4bd8-9e35-b01fc5a9945e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
