<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK</name>
   <tag></tag>
   <elementGuidId>a42f20b5-83bd-441e-917e-27b0bdab70a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;nik&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;nik&quot;]</value>
      <webElementGuid>d6401d68-90e6-42be-a3d7-cfa57d26eab7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
