<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StatusAutoSign</name>
   <tag></tag>
   <elementGuidId>f505d119-d5d0-4034-bdbf-2af3dee47477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;statusAutosign&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;statusAutosign&quot;]</value>
      <webElementGuid>68f37be2-4275-4779-bb9f-c27bd3827fbe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
