<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalLahir</name>
   <tag></tag>
   <elementGuidId>f2c8095c-e165-4f88-aea8-076e7ef6a53d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tanggalLahir&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tanggalLahir&quot;]</value>
      <webElementGuid>5adbcd4e-6cc3-4a3a-bf7a-df08e24de13f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
