<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoHandphone</name>
   <tag></tag>
   <elementGuidId>630625fd-e423-42cd-8e92-8a5800d0d7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;noHp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;noHp&quot;]</value>
      <webElementGuid>3f3a007b-5443-4657-8d8c-e99ecbacb7e9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
