<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_noTlp</name>
   <tag></tag>
   <elementGuidId>055ae62e-0fec-4298-84fa-0c0973dfa808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;noHp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;noHp&quot;]</value>
      <webElementGuid>6f77eb51-cb0e-4816-a6fe-92cf1fdeefdc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
