<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TutupDapatLink</name>
   <tag></tag>
   <elementGuidId>25fd41b7-0853-4107-89a1-8423cb9f29f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-view-invitation-link/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-view-invitation-link/div/div[2]/button</value>
      <webElementGuid>a95df718-7fff-4be0-a662-4f012137d33b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
