<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_YaBatalUndangan</name>
   <tag></tag>
   <elementGuidId>4959d625-6fc0-4590-ab35-61e9172804ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Ya' or . = 'Ya')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div/div[3]/button[3]</value>
      <webElementGuid>7c57b108-0c66-4fed-a6fd-dddd5d8bc1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>41d550fc-cc06-4587-98d6-e44bb05a6a2a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
