<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kecamatan</name>
   <tag></tag>
   <elementGuidId>0f2eec5e-816c-4d6b-b3bf-77ed7dfc7005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;district&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;district&quot;]</value>
      <webElementGuid>f1cc8799-5cfb-42c6-a498-4bdf70937fb9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
