<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AlamatLengkap</name>
   <tag></tag>
   <elementGuidId>e1da6c68-30ea-41d3-9122-ad2cfc3f1430</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;address&quot;]</value>
      <webElementGuid>df3d9b13-1d21-42c0-a5ea-3e98a1a4dec9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
