<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Wanita</name>
   <tag></tag>
   <elementGuidId>c9c7557c-485a-42aa-9aae-f763b00619f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;female&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;female&quot;]</value>
      <webElementGuid>c5735987-d46a-4f57-bae5-84622c7f4a7f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
