<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_RatingMasukan</name>
   <tag></tag>
   <elementGuidId>e9bd5089-3886-4b42-ac5c-a4b71471f2e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ngb-rating[@id='rating']/span[10]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f3d8c66-87ca-4807-9ec0-0061c627fabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-star-on px-2 ng-star-inserted filled</value>
      <webElementGuid>b68a5edb-2d8d-48cb-a3c9-c83f7d2ee85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rating&quot;)/span[@class=&quot;ng-star-inserted&quot;]/span[@class=&quot;ft-star-on px-2 ng-star-inserted filled&quot;]</value>
      <webElementGuid>746953c4-a448-4ca5-bcab-1d8398e83e81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngb-rating[@id='rating']/span[10]/span</value>
      <webElementGuid>20daa307-3fba-43cb-af95-195ecb9c0cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[10]/span</value>
      <webElementGuid>0693c27c-0fcb-4f2f-b050-f6c65f1a3074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
