<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_HeaderProsesTtd</name>
   <tag></tag>
   <elementGuidId>dc39ee5d-be73-474f-9746-e1c9f5cc81ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navtop']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.navbar-brand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4a26bd09-3986-4bac-85b5-9363577ee397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>69fafa6c-6a4a-4003-b20e-3707a71058e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanda Tangan Dokumen</value>
      <webElementGuid>f6c72e1b-ad79-4449-aefa-0941408df013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navtop&quot;)/a[@class=&quot;navbar-brand&quot;]</value>
      <webElementGuid>fa1d2e00-5a88-4f20-b02a-f4d9ac3ede1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navtop']/a</value>
      <webElementGuid>11620bf8-173d-4e69-8b3d-a8eb1dcd04b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tanda Tangan Dokumen')]</value>
      <webElementGuid>e3c2d8bd-bbad-4820-bd61-b2ec73a386bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DOKUMEN 1BM 1CUST'])[1]/preceding::a[1]</value>
      <webElementGuid>13d37bcb-02f2-436a-b788-897f618c39c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[1]/preceding::a[1]</value>
      <webElementGuid>4a49698c-c83d-41ec-9a0b-56406e76dfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tanda Tangan Dokumen']/parent::*</value>
      <webElementGuid>605799cd-fe58-44d9-b3ca-1acd98bc4ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>eab27224-6282-4919-9d59-3e7055f07340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Tanda Tangan Dokumen' or . = 'Tanda Tangan Dokumen')]</value>
      <webElementGuid>bbb99410-89e7-4461-8fa4-b5d23ed806c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
