<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>14798249-06da-42c3-a3c9-245c697cc3a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-user/div[2]/div/div/div/div/form/div[9]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-user/div[2]/div/div/div/div/form/div[9]/button[2]</value>
      <webElementGuid>d42a07d7-e3d7-4ca5-9d5f-a949bdb32173</webElementGuid>
   </webElementProperties>
</WebElementEntity>
