<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kembali</name>
   <tag></tag>
   <elementGuidId>e214ca39-b377-4a13-a250-7a4c0d4879cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-user/div[2]/div/div/div/div/form/div[9]/button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-full-layout/div/div[2]/div/div[2]/app-edit-user/div[2]/div/div/div/div/form/div[9]/button[1]</value>
      <webElementGuid>4b7df956-d65b-493d-adbe-f4e844508306</webElementGuid>
   </webElementProperties>
</WebElementEntity>
