<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_noHandphone</name>
   <tag></tag>
   <elementGuidId>47dd0d98-92cb-4508-8569-05c3c23f03fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;phone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;phone&quot;]</value>
      <webElementGuid>b9c238dd-3fa3-450f-bcbd-466aae9040d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
