<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TanggalLahir</name>
   <tag></tag>
   <elementGuidId>aec7a36d-a31a-400d-8911-c967d729307a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;dob&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dob&quot;]</value>
      <webElementGuid>a6cb896d-ce99-416a-91ee-d99c47396a7c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
