<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kota</name>
   <tag></tag>
   <elementGuidId>514d5976-08df-44eb-a04e-bcb6fa9752fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;city&quot;]</value>
      <webElementGuid>79827fe8-644b-49f4-a78f-f37985b8ec2c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
