<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kelurahan</name>
   <tag></tag>
   <elementGuidId>a10609de-7b66-470a-bb73-357704752062</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;subDistrict&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;subDistrict&quot;]</value>
      <webElementGuid>2818e1c3-ee1d-4a50-90e7-a03c7bad76d5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
