<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AlamatLengkap</name>
   <tag></tag>
   <elementGuidId>9cf93f24-54dd-4d4d-91f6-59fdd189e3ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;address&quot;]</value>
      <webElementGuid>2bf7c5ff-d39e-455d-af60-e367caa504f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
