<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Kecamatan</name>
   <tag></tag>
   <elementGuidId>e21236fa-3717-4fc3-b454-abac7ddcac0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;district&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;district&quot;]</value>
      <webElementGuid>9c93599f-f59f-4f19-8eb3-cd381f129dc3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
