<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MessagePopUp</name>
   <tag></tag>
   <elementGuidId>ca4cb2a8-6be1-4aa8-895d-aebb1d9d03e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;swal2-content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;swal2-content&quot;]</value>
      <webElementGuid>028f9d53-c969-4d87-bc98-d34937b1e73b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
