<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_E-Meterai</name>
   <tag></tag>
   <elementGuidId>b5df5e99-6c1d-4ddb-8ab3-28f882b94ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[8]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[8]/div/div/label</value>
      <webElementGuid>a0fc3a52-ea2c-478f-a8e5-cb14dd46d893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isMeterei</value>
      <webElementGuid>b786f09a-fc37-4be1-b3a1-2c91747274f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
