<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_E-Meterai</name>
   <tag></tag>
   <elementGuidId>b5df5e99-6c1d-4ddb-8ab3-28f882b94ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@for = 'isMeterei']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[11]/div/div/label</value>
      <webElementGuid>51617053-01cb-433a-9c02-60869b10ea67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>isMeterei</value>
      <webElementGuid>7d402d52-b0f6-4a5e-ab95-6268673dc121</webElementGuid>
   </webElementProperties>
</WebElementEntity>
