<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_closeddlOffice</name>
   <tag></tag>
   <elementGuidId>b9a1188a-d7f6-4d8d-80d4-e789d17f2d4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;officeCode&quot;]/div/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;officeCode&quot;]/div/span[1]</value>
      <webElementGuid>3982ef94-9302-4ff2-a06a-3ba03f828214</webElementGuid>
   </webElementProperties>
</WebElementEntity>
