<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_searchPenandaTanganWithEmailService</name>
   <tag></tag>
   <elementGuidId>5705135a-82e1-4748-8cc9-b9b971abb376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/ngb-modal-window/div/div/app-add-signer/form/div[2]/div[1]/div[2]/div/div/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a41c27c8-d561-4332-bce1-b629312b3612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-search</value>
      <webElementGuid>29bd7755-d669-4b99-8707-0d23a4a16cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-add-signer/form/div[2]/div[1]/div[2]/div/div/span/i</value>
      <webElementGuid>67da8e3a-4929-4c03-963b-fe9dc7636890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/i</value>
      <webElementGuid>7b6cebc8-6d58-4011-ac42-fab8c4f5a5dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
