<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tambahSigner</name>
   <tag></tag>
   <elementGuidId>0cd63ca2-4f7b-4ef1-bf30-15f2765cc514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[10]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[10]/div[2]/a</value>
      <webElementGuid>536457d9-d6a3-4044-8e7d-f2a3d424075c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
