<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_tambahTandaTangan</name>
   <tag></tag>
   <elementGuidId>b048f5e5-457c-4354-ba50-46d5aaa64574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='msxForm']/div[10]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-6.text-right > a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[10]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9162e9da-6df5-457a-a269-6845d93c24b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:</value>
      <webElementGuid>8dbb6d24-7dc3-474b-92d8-64878a364d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah</value>
      <webElementGuid>5ad6a996-a6f2-44b6-8f55-7a66fe94f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[10]/div[2]/a</value>
      <webElementGuid>7d10ce5b-9fd2-44c1-91c7-ce4233e93f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[10]/div[2]/a</value>
      <webElementGuid>ded938db-fa19-413c-a4f5-f089a63c95fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tambah')]</value>
      <webElementGuid>dd0a4bc4-2739-4722-858c-90def8d9860d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penanda Tangan'])[1]/following::a[1]</value>
      <webElementGuid>0d64f812-1399-485d-a4db-46ad50f1266a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak'])[1]/following::a[1]</value>
      <webElementGuid>28c9bef3-3c3e-449a-a64e-8e851d448b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum ada daftar penanda tangan!'])[1]/preceding::a[1]</value>
      <webElementGuid>e1a97153-f180-4023-abf6-36334153789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::a[1]</value>
      <webElementGuid>249fcfca-fcee-4d42-9003-d965312b3900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tambah']/parent::*</value>
      <webElementGuid>52db4419-ebee-4942-80ad-81a1fd7c47c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:')])[7]</value>
      <webElementGuid>8eaa917e-59b1-4f76-96d4-0739df61d715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>7ce0b65e-1d17-4855-8671-3985fc48c3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:' and (text() = 'Tambah' or . = 'Tambah')]</value>
      <webElementGuid>cb350554-000a-4bd1-8d97-eca23695cc15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
