<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_searchPenandaTangan</name>
   <tag></tag>
   <elementGuidId>5705135a-82e1-4748-8cc9-b9b971abb376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ft-search</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'ft-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2bd5fcd3-2421-4265-833a-d8d12530f2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ft-search</value>
      <webElementGuid>4cee246e-f311-45aa-9ddf-dd779abf9e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;input-group&quot;]/div</value>
      <webElementGuid>a4639b85-675f-46eb-b2ad-a4c200c5bfe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/i</value>
      <webElementGuid>3f68bb1d-1c64-48e6-82d0-fe610cc369cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
