<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog_PenandaTangan</name>
   <tag></tag>
   <elementGuidId>4997d2a7-a8df-49c5-a39d-de02b6531bb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'alert' and @type = 'danger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ngb-alert.alert.show.alert-danger.fade.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ngb-alert[@type='danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ngb-alert</value>
      <webElementGuid>b72b0e6b-4694-4453-be2d-a977085ee052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c3894e76-5ed8-494f-a7b2-33c6cef0c74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>9f4e5703-2492-4bba-bb3c-e54d650b9bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert show alert-danger fade ng-star-inserted</value>
      <webElementGuid>75299784-2008-47c2-a0e4-b11de846fc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-type</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>5ed8a25a-0234-4ccb-b21d-665d451cb04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-dismissible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41c15820-1cda-4d6d-9991-acb26a704c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User tidak ditemukan!</value>
      <webElementGuid>73b977a5-d3c2-434e-898f-503b1d7933df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@role = 'alertdialog']</value>
      <webElementGuid>b637503a-936b-4b66-8649-613980cfe7bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ngb-alert[@type='danger']</value>
      <webElementGuid>9978e20e-f61b-4ff1-a6d6-c386147ecbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penanda Tangan'])[1]/following::ngb-alert[1]</value>
      <webElementGuid>4b6a22e3-3496-4bc8-8f62-55e3514d4885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updates Available'])[1]/following::ngb-alert[1]</value>
      <webElementGuid>869f467a-1254-46bc-94f2-26fb59be188a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::ngb-alert[1]</value>
      <webElementGuid>235749d0-2ac8-4f5e-bddc-c4f0ee60244f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User tidak ditemukan!']/parent::*</value>
      <webElementGuid>7a425fb5-6e55-4f24-9e98-2e5d65153c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-alert</value>
      <webElementGuid>06cb76d3-8574-4cbc-985a-5bbbd1f2db4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ngb-alert[@type = 'danger' and (text() = 'User tidak ditemukan!' or . = 'User tidak ditemukan!')]</value>
      <webElementGuid>3c0829d5-6f48-4e8b-8d8f-38fab90bf6d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
