<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog</name>
   <tag></tag>
   <elementGuidId>311053f9-8e93-4ada-b2e8-8853a579e739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class=&quot;overlay-container&quot;]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overlay-container/div</value>
      <webElementGuid>9e9ace69-5672-4ff4-b761-3bb2a70d12af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class=&quot;overlay-container&quot;]/div/div/div</value>
      <webElementGuid>b732148f-4ee5-4024-9737-a0e5f4787095</webElementGuid>
   </webElementProperties>
</WebElementEntity>
