<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog_PenandaTangan</name>
   <tag></tag>
   <elementGuidId>4997d2a7-a8df-49c5-a39d-de02b6531bb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ngb-alert.alert.show.alert-danger.fade.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ngb-alert[@type='danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ngb-alert</value>
      <webElementGuid>8c3baad8-7aee-440d-b765-ab4623db6614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>c4aa2ac3-49a0-4771-85c2-99b8d63e9558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>9bfcd261-8357-468e-83db-7016a9afeda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert show alert-danger fade ng-star-inserted</value>
      <webElementGuid>90d4cdad-04e4-4df2-a662-a1d4e3fe27ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-type</name>
      <type>Main</type>
      <value>danger</value>
      <webElementGuid>eb80b519-b8d0-41eb-8b9d-03337f1ff03d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-dismissible</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>23147e85-74b9-447b-ab5d-bf0e0d268d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User tidak ditemukan!</value>
      <webElementGuid>decfa7d5-1236-4057-9e7e-2ba69db4f1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;vertical-layout menu-expanded menu-open vertical-menu navbar-static pace-done navbar-scrolled page-scrolled modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/app-add-signer[1]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;modal-body&quot;]/ngb-alert[@class=&quot;alert show alert-danger fade ng-star-inserted&quot;]</value>
      <webElementGuid>c1519889-000c-4e3a-831e-c32befc46e3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ngb-alert[@type='danger']</value>
      <webElementGuid>4a5c0e76-2a45-41a1-9e87-662349fab6c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Penanda Tangan'])[1]/following::ngb-alert[1]</value>
      <webElementGuid>d42a2dd5-3d9e-4a3d-93f9-a5e9935895c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Updates Available'])[1]/following::ngb-alert[1]</value>
      <webElementGuid>359091d2-f58d-4912-a488-d09913f7fe10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::ngb-alert[1]</value>
      <webElementGuid>bba20d32-ccbc-4e3e-9806-e2a018cd9da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User tidak ditemukan!']/parent::*</value>
      <webElementGuid>996e8b6d-a9c8-4d53-8c3b-bfc434370dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-alert</value>
      <webElementGuid>ea527038-d17b-402a-be52-4df9102188d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ngb-alert[@type = 'danger' and (text() = 'User tidak ditemukan!' or . = 'User tidak ditemukan!')]</value>
      <webElementGuid>5afff578-1ef5-41a3-962c-9b6d5722f44d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
