<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_officeCode</name>
   <tag></tag>
   <elementGuidId>a89ef93f-5b6c-4da9-b3c9-037aaeae1768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;officeCode&quot;]/div/div/div[3]/input</value>
      <webElementGuid>8204c8f9-23fd-46ba-a921-3b760047a99b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
