<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_referenceNo</name>
   <tag></tag>
   <elementGuidId>dc7c84a2-49cb-4d39-b9ea-0923aeac2f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referenceNo</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'referenceNo']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='referenceNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0038fa8c-d712-46ae-b305-b8e318fd4a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>937dc7f3-9e13-4203-870d-7d7ea3abca6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0fe697b0-01dd-4cf7-8391-2fbb4fa63019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>referenceNo</value>
      <webElementGuid>b010590d-f0b4-4269-a1b1-9d58d390ec92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referenceNo</value>
      <webElementGuid>3ef0a531-4dac-4959-9a36-9538ae4cf03f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type document number here</value>
      <webElementGuid>df919fc0-816f-4e72-9a18-c436034ae1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b04e4dfc-3ff7-4bf8-9eea-7d607666d608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>32e2eec6-0cc8-45e7-a68e-cb15801068ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referenceNo&quot;)</value>
      <webElementGuid>3944c03a-31b6-456a-a407-a568d9777c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='referenceNo']</value>
      <webElementGuid>77148eae-d19e-468a-ad1d-efe42c82bbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[2]/div/app-text/fieldset/div/input</value>
      <webElementGuid>e37875cb-f98c-4232-b460-a5f3555e4ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>ce2c3dbc-4c47-4115-883c-e3f0ff51cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'referenceNo' and @placeholder = 'Type document number here']</value>
      <webElementGuid>13bc04d7-660c-4813-b6db-4a459b9ba8fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
