<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tipeDokumenPeruri</name>
   <tag></tag>
   <elementGuidId>f86cbbcd-ed65-49ff-b426-570145654488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentTypePeruri > div.ng-select-container.ng-has-value > div.ng-value-container > div.ng-input > input[type=&quot;text&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;documentTypePeruri&quot;]/div/div/div[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d4194db-4580-41f0-8a71-a66f99b6fa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>788ae9f9-2994-4a3c-b4e3-032e4664272d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6428840a-6332-4fc3-9210-f016cc166b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a68da76f-8867-4f09-ad00-a127f0590da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>07cfc036-b746-4bc6-81eb-9e3d7288be4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>a521691694b8</value>
      <webElementGuid>fc857f61-39aa-47f2-a60e-a1948a892fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4592f771-7c2c-4478-8826-7b2d40874fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>a521691694b8</value>
      <webElementGuid>cdb23745-4280-44e0-979e-d3682952f029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a521691694b8-0</value>
      <webElementGuid>11afdfe0-28e3-456a-bf3f-aba44525ea6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;documentTypePeruri&quot;]/div/div/div[3]/input</value>
      <webElementGuid>8c6b0970-b162-4f4c-896d-e3c869a2f951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentTypePeruri</value>
      <webElementGuid>a370bb2f-2f42-4fc6-aa06-95b20a30029f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>98648755-9b62-4abf-92cf-f6c4828d1c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='documentTypePeruri']/div/div/div[3]/input</value>
      <webElementGuid>8d2a56a4-a795-41da-acfe-3f509f254306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/app-select/div/ng-select/div/div/div[3]/input</value>
      <webElementGuid>62bfcbe6-a369-4dfc-af3f-4ebffe630590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>02dc46bc-fe10-473a-890a-5d2eaa378205</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
