<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentDate</name>
   <tag></tag>
   <elementGuidId>037b2b1d-9411-4b25-8be5-0111b87bcf26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'documentDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e6906d6-8edd-49a7-91a7-b46413eedf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a544716b-cb61-40e2-a1a3-f12712a57897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>966a901a-21be-4988-ac73-9a6ff28bcc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentDate</value>
      <webElementGuid>7331966a-e0d9-4de9-9ed6-1a3e1c6aad13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentDate</value>
      <webElementGuid>be031fea-4873-48be-8419-3052769e74c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>383218d2-15df-40f9-9186-46d2970dbf7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentDate&quot;)</value>
      <webElementGuid>5cb2ec8a-594e-4857-9a13-4a7c60efd6c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentDate']</value>
      <webElementGuid>e09a1d4a-f9df-4303-bd55-401995fa7ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[4]/div/app-date/fieldset/div/input</value>
      <webElementGuid>5efd28e3-4409-4164-b954-2b2fadd07532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>a9692710-b389-48b6-bf54-45535556f4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>69ddbd78-6a15-44c9-a19f-39e9c8ac6606</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
