<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__referenceNo</name>
   <tag></tag>
   <elementGuidId>dc7c84a2-49cb-4d39-b9ea-0923aeac2f65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#referenceNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='referenceNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c2362da-9848-4274-8607-a93f2b98d54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d4751b5-9c97-48b1-a30e-cf6b6f625884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b8542d89-dabb-4bd0-8606-41706f355924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>referenceNo</value>
      <webElementGuid>699dd803-c4f5-4a87-80fb-33e294c0cdab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>referenceNo</value>
      <webElementGuid>ccd65780-4abc-4685-a475-5fb4f576f656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type document number here</value>
      <webElementGuid>8a6c428c-5941-4735-a8a0-7c8a1bcfc340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>41d3b7a6-21e6-4fbf-b4d9-bfe2700b6665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>1ef4e583-79d0-450e-85a0-233f727e8ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;referenceNo&quot;)</value>
      <webElementGuid>8958eba5-5db7-454a-ae23-84a378b48007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='referenceNo']</value>
      <webElementGuid>62bccc29-c614-4dcd-9d99-f06aa3e5d755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[2]/div/app-text/fieldset/div/input</value>
      <webElementGuid>36060ed0-da61-4019-925d-163a305047f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>808b77ae-dacd-416d-b8f4-6988f5a836d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'referenceNo' and @placeholder = 'Type document number here']</value>
      <webElementGuid>6924e093-0489-4164-b32c-bd7a9b6bbfc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
