<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__documentName</name>
   <tag></tag>
   <elementGuidId>a3f12a68-9d91-409b-9ae8-7c23f857a481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c7fe1ce-0f7e-474b-b686-251d82a51531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ccf1bf5f-052f-4d09-8d86-c326681621ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>7675c207-4af6-4674-9942-28c13d201d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>c77e7bc0-fb0d-445e-bc4d-cbbf88e51f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>f00b0c99-a8f6-4dd6-85d3-5841ab8843f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nama dokumen</value>
      <webElementGuid>574b6f4a-b2ac-4627-8ecf-93a4aa467420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>810ad73d-008d-4328-a40d-6e7e80a8d826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>de02dc3a-bd97-4281-8c1b-1c0908ef8f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentName&quot;)</value>
      <webElementGuid>4e40452c-5dce-4cd3-8f3b-c5dad97f8c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>cdfe8129-dd57-4b8f-b35b-5c96e0fd3e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>2f0edd5e-9909-4402-abbe-5936ddbafd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>d4ba5778-6876-4435-a96f-04357e3accb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Tulis nama dokumen']</value>
      <webElementGuid>36141934-8ed8-4019-9869-aa579128fe99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
