<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_officeCode</name>
   <tag></tag>
   <elementGuidId>a89ef93f-5b6c-4da9-b3c9-037aaeae1768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;officeCode&quot;]/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;officeCode&quot;]/div/div/div[2]/input</value>
      <webElementGuid>c8da16e7-92d4-4d53-9136-c756f3469551</webElementGuid>
   </webElementProperties>
</WebElementEntity>
