<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentDate</name>
   <tag></tag>
   <elementGuidId>037b2b1d-9411-4b25-8be5-0111b87bcf26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'documentDate']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e7d6016-758e-42cf-8e94-b7358a4c51b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cdd986f-c545-460b-8ede-acfc724615a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>06755e7a-2027-4fcd-aabb-74a39fafb63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentDate</value>
      <webElementGuid>43bdab95-87f5-4b87-bc82-40170967ee0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentDate</value>
      <webElementGuid>b2c9a54e-7176-4c6f-a546-bf1581ea997a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-mm-dd</value>
      <webElementGuid>9d87e9a2-f7d5-4890-a683-f6e2a12d5fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentDate&quot;)</value>
      <webElementGuid>36983ecd-90c1-44d2-bc68-092bdf3a022a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentDate']</value>
      <webElementGuid>e9f4b82a-ec73-4cf2-b22a-891d13fdec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[4]/div/app-date/fieldset/div/input</value>
      <webElementGuid>d2a36488-86d1-4855-8518-1a0ef7f9d142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-date/fieldset/div/input</value>
      <webElementGuid>88d7bbbd-99c8-45c9-b950-f1a1afc4dfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentDate' and @placeholder = 'yyyy-mm-dd']</value>
      <webElementGuid>88d664e2-e5a8-4e73-bdf1-5adf8ad225f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
