<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentName</name>
   <tag></tag>
   <elementGuidId>a3f12a68-9d91-409b-9ae8-7c23f857a481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@ng-reflect-name = 'documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0812b6e-f90d-4894-8305-54f3c6b7a2cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9aaa7f25-2d92-4d57-903d-4fa445b3765a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>fe12585b-6994-4335-a779-0705dea76797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>46995c71-3a84-41b5-9a17-b470b7c3f96d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>08d5a44e-b1a3-4fd8-8dec-8595d04470ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nama dokumen</value>
      <webElementGuid>5e0fc04e-5ba6-4cf0-b01d-c3782d178daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f9ab398-347a-42d3-ae38-90e2ff6d584b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a3a145e3-6f9b-4a5f-ba0f-6af689d16648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentName&quot;)</value>
      <webElementGuid>bfe3b3b1-8cbc-4495-80da-1a0a453ebd70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>2b490d81-59cd-4e94-ac63-61bb57645f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>eebea776-4dfc-4fea-b9cc-aaea1981e59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>09566cd2-df9f-4a4b-9031-c062f4c733f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Tulis nama dokumen']</value>
      <webElementGuid>68bc5790-a3ad-4ba5-bb24-0883067c9b05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
