<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_documentName</name>
   <tag></tag>
   <elementGuidId>a3f12a68-9d91-409b-9ae8-7c23f857a481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'documentName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4525ed5b-bb58-4210-8913-56188e98641c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7bd0d5e1-4e94-4b0a-9e7a-1915858e86fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>f560bc02-dd6b-4163-bbfe-145fc550320a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>39059bfc-853b-4756-a034-aa9369735cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>26de9602-3e36-473d-aaab-043472fcfe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tulis nama dokumen</value>
      <webElementGuid>640c70df-274d-4601-9b53-c9659323d0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a7403cf-e0cd-413e-97d8-10ed4c87d8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0b2d67b1-0184-4e70-92ba-8269151a4793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentName&quot;)</value>
      <webElementGuid>998029f5-debe-442f-857a-774512eeae07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>b1276a4f-70b5-49fd-809e-067aae5b8621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>b8b63f01-b549-4990-ac52-3c203711cd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/app-text/fieldset/div/input</value>
      <webElementGuid>def7e8bb-0962-4eb9-b72a-299f3e71241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Tulis nama dokumen']</value>
      <webElementGuid>bd9e54c8-323e-4e2a-9efc-909fe927d347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
