<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_daftarpenandatangan</name>
   <tag></tag>
   <elementGuidId>1ccf31b0-de95-4b4a-a11b-14cc6b2d9d10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;msxForm&quot;]/div[8]/div[3]/table/tr/td/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;msxForm&quot;]/div[8]/div[3]/table/tr/td/small</value>
      <webElementGuid>b4cf13ce-1438-41cb-93a2-1ce6e78baf2d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
