<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modifyObject</name>
   <tag></tag>
   <elementGuidId>882ff92a-b3ad-4d9c-b372-2e40335f7230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;isActive&quot;]/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;isActive&quot;]/div/span[2]</value>
      <webElementGuid>04bc92ab-46ef-4cbf-b590-a75eaa519eb6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
