<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_informasiPenandaTangan</name>
   <tag></tag>
   <elementGuidId>93ed9da3-cb3e-4ba8-a05c-0d26456d02bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'USERCIIE 081233444403,  USERCIIE@AD-INS.COM ' or . = 'USERCIIE 081233444403,  USERCIIE@AD-INS.COM ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='msxForm']/div[10]/div[3]/table/tr/td/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>eb9a3970-ffe7-478b-b50e-4dc10ea152ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USERCIIE 081233444403,  USERCIIE@AD-INS.COM </value>
      <webElementGuid>b9aee9d2-71a4-4413-b1ea-6d7464919d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;msxForm&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/table[@class=&quot;table table-striped table-hover&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[1]/p[1]</value>
      <webElementGuid>a781875b-700f-4c66-b751-25f78a17350d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div[10]/div[3]/table/tr/td/p</value>
      <webElementGuid>ab98695c-693d-4eaa-b5f4-4eef819a22ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah'])[1]/following::p[1]</value>
      <webElementGuid>3490b0a5-0caa-4724-9edf-71ca9bb1c326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penanda Tangan'])[1]/following::p[1]</value>
      <webElementGuid>b7e2abbf-8dbe-4755-b41d-d484d20843d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal'])[1]/preceding::p[1]</value>
      <webElementGuid>ce30aab7-30e9-4841-934a-be4a993d3fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='081233444403,']/parent::*</value>
      <webElementGuid>95c034f0-8503-4db7-b456-3ed1e870c630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>2f1777e3-e56e-4fda-a498-ccb0eca5eee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'USERCIIE 081233444403,  USERCIIE@AD-INS.COM ' or . = 'USERCIIE 081233444403,  USERCIIE@AD-INS.COM ')]</value>
      <webElementGuid>55da8557-1805-45e2-b548-520f0569441d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
