<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_namaDokumen</name>
   <tag></tag>
   <elementGuidId>b4427b79-6e52-4b23-b7f7-973a015016f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>149a7a23-5075-4228-9cc5-f458af80069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c4524f1-9739-4001-80b0-342f2deee336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>7861e9d5-0694-449f-a066-e677599e5547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>b85819c9-59c5-4eaf-ac78-21794f046810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>2efbc9a1-12d2-4a3a-89ce-6c602bc4e758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Document template name</value>
      <webElementGuid>358d5414-e4d6-4efe-9759-05a39ac57080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentName&quot;)</value>
      <webElementGuid>63d0fab4-e4a0-4766-a95a-5d2aa233f213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>fbcd543b-45f8-4760-b98f-17c5a6d40ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>234eb8dc-7577-4759-b89c-2a75bb2ce304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>5817298d-36ae-41a7-abe3-715ab4c47b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Document template name']</value>
      <webElementGuid>4e5f5378-8c69-4cad-9490-99a42b9ebf9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
