<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_namaDokumen</name>
   <tag></tag>
   <elementGuidId>b4427b79-6e52-4b23-b7f7-973a015016f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentName</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'documentName']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='documentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb76cdf6-cd4b-4369-b7ba-031852ce6212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60151e76-626a-4a29-b180-077c17dba427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>762f4c4d-37f3-4a8f-baa2-82080abd216e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>8a9edf35-c060-4a60-ba4f-0a7fab31127d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentName</value>
      <webElementGuid>9e79c7d7-6f79-4c7d-b21d-4581cb588733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Document template name</value>
      <webElementGuid>beaf13da-44eb-4e31-aef5-df0f5bdadd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentName&quot;)</value>
      <webElementGuid>aae17cc1-027e-4676-b7c1-fb5e1177d1c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='documentName']</value>
      <webElementGuid>34046255-1160-4916-be0d-fd02a731239e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='msxForm']/div/div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>3568723a-8a49-4b37-9c70-d6ce9ad8efcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/app-question/app-text/div/div[2]/div/input</value>
      <webElementGuid>532656ad-a91f-42fe-b44e-5e7a8751b6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'documentName' and @placeholder = 'Document template name']</value>
      <webElementGuid>de8034f7-3d1d-4d99-b2f9-a6541531305e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
