<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_TutupDapatLink</name>
   <tag></tag>
   <elementGuidId>e72a6d33-05ff-4a48-bde0-2f7e62a9820a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Tutup' or . = 'Tutup')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/ngb-modal-window/div/div/app-view-invitation-link/div/div[2]/button</value>
      <webElementGuid>e24247e6-dea5-4cd1-84b6-a500c4aea6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tutup</value>
      <webElementGuid>1b40be54-31ce-421b-b20d-deaaf086d3e7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
