<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>edit_Nama</name>
   <tag></tag>
   <elementGuidId>9554f95a-9527-4633-9a31-f56d24ae694e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;name&quot;]</value>
      <webElementGuid>0c1ec367-c93d-4b7c-a3ea-16bd827b9ac8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
