<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorLog</name>
   <tag></tag>
   <elementGuidId>dbcf2126-f2cc-4769-a8a6-66aa728a5820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@role = 'alertdialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/div/div[2]</value>
      <webElementGuid>306a78aa-79b2-4f54-8b02-2c72747f2eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alertdialog</value>
      <webElementGuid>542056ef-01d0-452c-9150-0af6821d62da</webElementGuid>
   </webElementProperties>
</WebElementEntity>
