<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SearchBox</name>
   <tag></tag>
   <elementGuidId>a1fea183-941c-40c5-a0fa-3cae6aacd5ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;param&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;param&quot;]</value>
      <webElementGuid>de90cc92-3d0f-481e-b9c0-e1ea37322deb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
