<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Male</name>
   <tag></tag>
   <elementGuidId>9dc28286-fd7f-4697-9330-d6f3e8f436d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;male&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;male&quot;]</value>
      <webElementGuid>bc905a7a-86a9-497f-be03-3fb314efbc35</webElementGuid>
   </webElementProperties>
</WebElementEntity>
