<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>intut_UlangKataSandi</name>
   <tag></tag>
   <elementGuidId>0875be77-54be-4e07-b75f-eabee660e881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;password2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;password2&quot;]</value>
      <webElementGuid>7726b1e9-811d-4418-b5e4-0cec4514c849</webElementGuid>
   </webElementProperties>
</WebElementEntity>
