<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_AlertUlangKataSandi</name>
   <tag></tag>
   <elementGuidId>4bef0c44-3b48-4a4d-824f-b22c107c8fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;null_confirm&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;null_confirm&quot;]</value>
      <webElementGuid>699690bf-1aef-4a5c-a4b0-4521c43eac18</webElementGuid>
   </webElementProperties>
</WebElementEntity>
