<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>switch_SyaratKetentuan</name>
   <tag></tag>
   <elementGuidId>b3086700-5c4f-438f-8b25-3d40b615ef57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formAktivasi&quot;]/div[5]/div/div[2]/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formAktivasi&quot;]/div[5]/div/div[2]/label/span</value>
      <webElementGuid>399470fc-097d-48eb-916e-c81ae701d22f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
